### ISSUE TITLE
P#51787 Fix display of parking lots

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#295]
# Current state
When outputting the field "multiParkingLot' only the word "Array" is displayed instead (see Frontend_Error_current.png) instead of a readable output.

# Desired state
1. The field should be output as string in the template. (Do not make the field a string until it is displayed in the template, so that it is in principle possible to change how the values are displayed in future templates.) The parking lot information should be accessible in a structured way from within the template (as an array)

2. The value of the field should be displayed in the list and detail view the same as in enterprise using the correct language.
    ![Enterprise_parking](https://user-images.githubusercontent.com/90763364/182403752-4ecfd8f0-597e-4db2-9cf6-cb8ed44444f0.PNG)

    1. Multiple values should be separated by commas: "1 garage at €500 (purchase), 10 free parking lots at €45.99 each (rent)"

    2. The translators should be able to place each variable how they need to. Notice that in English there is an "each" between the \<single price> and the \<marketing type>. Therefore use the [sprintf approach](https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/105#issuecomment-1182882436) (we should use that approach in general for combining strings).

        English: \<Number of parking spaces> \<type> at \<single price> each (\<marketing type>)
        German: \<Number of parking spaces> \<type> à \<single price> (\<marketing type>)
        Examples:
        English: "1 garage at €500 (purchase), 10 free parking lots at €45.99 each (rent)"
        German: "1 Garage à 500 € (Kauf), 10 Freiplätze à 45 € (Miete)"

5. The currencies should be localized.
    1. The prices should be formatted using NumberFormatter (https://www.php.net/manual/en/class.numberformatter.php) and the current locale (get_locale(), https://developer.wordpress.org/reference/functions/get_locale/).

    3. If the php intl extension is not installed, we cannot use NumberFormatter. I could not find data on how often the extension is not available. Since the NumberFormatter is only used for the parking lot field, which is currently broken anyway, crashing at this point should not break more. Therefore for now we just use NumberFormatter and see how many reports we get that it does not work.

    4. Prices should use the currency from estate. They have a field `waehrung` which contains the currency. If the `formatoutput` flag is not set, then the currencies are returned in the form "EUR" instead of "€". This is good, because NumberFormatter uses this format:
        ```
        $currencyFormatter = new NumberFormatter("de", NumberFormatter::CURRENCY);
        echo $currencyFormatter->formatCurrency(12345.12345, "EUR");
        // --> 12.345,12 €

        $currencyFormatter = new NumberFormatter("de-AT", NumberFormatter::CURRENCY);
        echo $currencyFormatter->formatCurrency(12345.12345, "GBP");
        // --> £ 12.345,12

        $currencyFormatter = new NumberFormatter("en", NumberFormatter::CURRENCY);
        echo $currencyFormatter->formatCurrency(12345.12345, "GBP");
        // --> £12,345.12
        ```

**Comment by jmaas-onoffice** [comment]
- Improved 2. to suggest a better approach for combining strings.
- Simplified and better explained how we want to handle the currency in 3.

**Comment by hungnc89** [comment]
@jmaas-onoffice Which currency I need to use when locale is `en`? £ or €

![image](https://user-images.githubusercontent.com/72601287/184119995-bd2b4f06-95a9-4f06-a179-018e5fc07e25.png)
![image](https://user-images.githubusercontent.com/72601287/184119962-db040147-1d65-447c-abd0-e5d020efb433.png)

**Comment by jmaas-onoffice** [comment]
It is possible to not show insignificant decimals.

```php
<?php
$amount = 123;
$currencyFormatter = new NumberFormatter("de-DE", NumberFormatter::CURRENCY);
$currencyFormatter->setAttribute(NumberFormatter::ROUNDING_MODE, NumberFormatter::ROUND_UP);
if (intval($amount) == $amount) {
    $currencyFormatter->setAttribute(NumberFormatter::MIN_SIGNIFICANT_DIGITS, 0);
}
echo $currencyFormatter->formatCurrency($amount, "EUR");
// --> 123 €
```
