### ISSUE TITLE
Improve creation of new forms

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#358]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/340

<div type='discussions-op-text'>

<sup>Originally posted by **jmaas-onoffice** October  5, 2022</sup>
## The button for creating new forms is hidden
When new users first go to the forms, there is no button for adding new forms.

![image](https://user-images.githubusercontent.com/90763364/194091532-9bad961f-ed21-48fa-b53a-9ba8e6dca7f6.png)

They need to know that they have to first choose a form type from the list filters. Then there is a button for creating a new form of that type.

![image](https://user-images.githubusercontent.com/90763364/194091556-0413ee19-4e5d-4cc5-ac11-5b2d1510ee70.png)

## Offer a button dropdown
As a 1-week project, I propose that we instead offer a button dropdown on all pages.

The button should be visible on the overview and on each form type filter page.

![image](https://user-images.githubusercontent.com/90763364/194091585-b794f985-477a-4546-a9a0-05eb39847e1a.png)

When the button is clicked, a dropdown should appear that lists the different form types. After selecting one, a new form of that type is created.

![image](https://user-images.githubusercontent.com/90763364/194091622-3fe25047-2414-4c10-a9a3-d565c2092fcf.png)

(The sketch is only a suggestion. You can do something different, if there are advantages to do so.)</div>

**Comment by dai-eastgate** [comment]
@jmaas-onoffice  I created a button dropdown, you can watch video and give me feedback.
https://user-images.githubusercontent.com/106214469/198557693-f0366f26-dc7c-46f9-8b7c-7d8beccbef7e.mp4

**Comment by jmaas-onoffice** [comment]
Seems to work well!

However, it looks very different from the other WordPress UI elements. Could you make the button look more like the existing button (plus a "v" to indicate that a dropdown will open) and the dropdown closer to how it looks elsewhere in WordPress?

![image](https://user-images.githubusercontent.com/90763364/198580754-67620b5d-0803-4f70-8551-69a867fcffa8.png)

**Comment by dai-eastgate** [comment]
> Seems to work well!
> 
> However, it looks very different from the other WordPress UI elements. Could you make the button look more like the existing button (plus a "v" to indicate that a dropdown will open) and the dropdown closer to how it looks elsewhere in WordPress?
> 
> ![image](https://user-images.githubusercontent.com/90763364/198580754-67620b5d-0803-4f70-8551-69a867fcffa8.png)

I will fix.
