### ISSUE TITLE
Improve addition and removal of fields

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#359]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/339

<div type='discussions-op-text'>

<sup>Originally posted by **jmaas-onoffice** October  5, 2022</sup>
## Adding and removing fields is unintuitive
Users can configure which fields to show for address and estate lists and forms. However, adding and removing fields is unintuitive.

In order to add a field, you have to check it in the selection on the left side and then click the button "Add" below each section.

The only way to remove a field is to expand it and click the deletion link.

## Allow direct addition and removal from the field selection
As a 1-week project I propose that we make the interactions more intuitive.

In the field selection, you should be able to add a field with one click.

Similarly, you should be able to see which fields are already in the list and remove them with one click.

![image](https://user-images.githubusercontent.com/90763364/194080725-1bb6709a-4465-4172-9871-ff9cb44b00c1.png)

(The sketch is just a suggestion, you can do something different if it has advantages to do so.)</div>

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I improved addition and removal of fields. You can watch video and give me feedback.

https://user-images.githubusercontent.com/106214469/198953992-6e67fcd5-4b5e-4312-9921-121e7c19a4f5.mp4

**Comment by jmaas-onoffice** [comment]
This looks great! 🎉 

Just some minor ideas:

- When an item is added, can we make the text less opaque? For example like this:
  ![image](https://user-images.githubusercontent.com/90763364/198966375-d27afae7-4bb7-42e5-a3e0-e2c41ec7b4a1.png)
- In your video, when you click the + or -, a text cursor appears. This did not happen for me in Edge. But could you ensure that there is no text cursor when using the button?

**Comment by dai-eastgate** [comment]
> This looks great! 🎉
> 
> Just some minor ideas:
> 
> * When an item is added, can we make the text less opaque? For example like this:
>   ![image](https://user-images.githubusercontent.com/90763364/198966375-d27afae7-4bb7-42e5-a3e0-e2c41ec7b4a1.png)
> * In your video, when you click the + or -, a text cursor appears. This did not happen for me in Edge. But could you ensure that there is no text cursor when using the button?

I will fix.
