### ISSUE TITLE
Incomplete uninstallation

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#361]
I recently had to re-install the plugin and noticed that the uninstallation script leaves some options:

![image](https://user-images.githubusercontent.com/90763364/197221297-f4be7327-726e-4c4c-a699-f60261c16bce.png)

The uninstallation should remove all the plugin's data.

**Comment by dai-eastgate** [comment]
I just uninstalled above 2 options in task https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/118 you can check PR
! [image](https://user-images.githubusercontent.com/106214469/198493026-7d910680-1234-4506-959a-e175936813f0.png)

**Comment by hungnc89** [comment]
@jmaas-onoffice could you help me check this issue finished and can close ?

**Comment by jmaas-onoffice** [comment]
Oh, I seem to have missed Dai's comment! Sorry about that!

You're right, this issue does not occur anymore on v4.5. 🎉
