### ISSUE TITLE
Fatal error when API credentials are not valid

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#368]
When I enter invalid API credentials (for example I mistype the token, or I switch token and secret), on every page load there is a fatal error that prevents the UI from fully showing. This breaks the entire website.

To get the website working again, you need to disable the plugin, e.g. by renaming its folder via FTP, and then go to /wp-admin/options.php and fix the credentials (search for `onoffice-settings-apisecret`). Or you can deinstall and reinstall the plugin to reset the settings.

The error message is:
```
[07-Nov-2022 09:29:29 UTC] PHP Fatal error:  Uncaught {
    "actionid": "urn:onoffice-de-ns:smart:2.5:smartml:action:get",
    "resourceid": "",
    "resourcetype": "estateCategories",
    "parameters": []
}

errorCode: 500

onOffice\WPlugin\API\APIEmptyResultException in /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/API/APIClientExceptionFactory.php:50
Stack trace:
#0 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/API/APIClientActionGeneric.php(85): onOffice\WPlugin\API\APIClientExceptionFactory->createExceptionByAPIClientAction(Object(onOffice\WPlugin\API\APIClientActionGeneric))
#1 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/API/APIClientActionGeneric.php(136): onOffice\WPlugin\API\APIClientActionGeneric->generateException()
#2 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Fieldnames.php(18 in /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/API/APIClientExceptionFactory.php on line 50
```

**Comment by jmaas-onoffice** [comment]
@dai-eastgate @LongTrong-exe This is quite a critical bug. The cycle ends Wednesday anyway, so finish up the bets, but then it would be great if you could prioritize diagnosing this bug to figure out a fix.

**Comment by dai-eastgate** [comment]
https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/368#issuecomment-1305353136
yes we will check and fix it

**Comment by jmaas-onoffice** [comment]
If there is not a trivial fix, we can figure out a solution together. ;)

**Comment by jmaas-onoffice** [comment]
This not only happens, when I switch the token and secret, but whenever the credentials are invalid.

**Comment by dai-eastgate** [comment]
I think if api errorCode 500 instead of showing error we can show message to user and update default(API token and API secret). What do you think about this?

**Comment by jmaas-onoffice** [comment]
Oh, so it seems that the API was returning a different error code than our code expected. And because our code only handled that one specific error code, the exception was unhandled and crashed everything.

I just tested it again and now I can't reproduce the problem. It seems the API now responds with the expected error code.

But this issue demonstrates that we cannot allow exceptions to go unhandled here. I think it would be nice, though, to distinguish between a problem with the credentials and another exception.

So could we add an additional error message, when it's not an invalid credential exception, but something unexpected? In that case we would not want to tell the user that something is wrong with their credentials, but instead just that there is a problem with the API.

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I added an additional error message when it is not an invalid credential exception. You can watch the video and give me feedback.
https://user-images.githubusercontent.com/106214469/201020134-dd0bfb2b-0514-413a-a7ba-4750a9349916.mp4

**Comment by jmaas-onoffice** [comment]
That looks good! The other pages are usable. 👍 

So the most important requirement is that no exception should make all pages unusable. It's ok if the plugin's pages are unusable.

We could also improve the error message a bit:

"""
The onOffice plugin has an unexpected problem when trying to reach the onOffice API.

Please check the [onOffice server status](https://status.onoffice.de/) to see if there are known problems. Otherwise, report the problem using the [support form](https://wp-plugin.onoffice.com/en/support/).
"""

When the fix is done, feel free to merge it into master and notify me. :)

**Comment by dai-eastgate** [comment]
> 

@jmaas-onoffice yes, I fixed it and merged it into master
