### ISSUE TITLE
Style new form dropdown more consistently

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#370]
## The current dropdown has an inconsistent style

This is the new dropdown button for adding any form: 
![image](https://user-images.githubusercontent.com/90763364/201056279-c385c366-b88f-4cd3-bdf7-c6e12dedf559.png)

(Sorry for the German interface. I hope the idea still comes across.)

This is how the button looks like when filtering for a specific form type:
![image](https://user-images.githubusercontent.com/90763364/201056451-8e0fbead-0bb7-4712-8add-b0e3d412557c.png)

## Use a more consistent style
To make it easier to understand that the dropdown functions similarly to the other buttons, we should style it similarly:
![image](https://user-images.githubusercontent.com/90763364/201056586-ba9c8511-af63-4da6-bdb9-146af4c4f4e9.png)

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I fixed, you can watch video and give me feedback.

https://user-images.githubusercontent.com/106214469/201288419-a2e7c9ab-5afc-4353-b8cb-680a2d201e9d.mp4

**Comment by jmaas-onoffice** [comment]
Very nice! Thank you!

By the way, I think I should have given you the design right away. I'll discuss with Linh next weekly what a good balance is for the requirements. ;)
