### ISSUE TITLE
Help users when detail view shortcode does not have ID

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#373]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/364

<div type='discussions-op-text'>

<sup>Originally posted by **jmaas-onoffice** October 24, 2022</sup>
> Time-tracking ticket: T#3258529

This change was bet on in the [cycle until 2022-10-11](https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/333), but there were some issues so it was dropped.

## Users don't understand the error message
Currently, when users want to preview the detail page, they are presented with this error message:
![grafik](https://user-images.githubusercontent.com/90763364/190999375-956a018f-ad53-45ec-ba0f-d56904a1bed4.png)

We often receive questions what to do about this, because users cannot know that they need to go to the estate list and choose an estate there to open the URL with a valid ID.

## Give instructions on what to do
Instead of showing the error message, we should tell users that they need to go to an estate list and open an estate detail page from there. I propose this as a 1-week project.

If the user is logged in, we should additionally allow them to easily open a random estate's detail page. This should not be available publicy, only when the user is logged into WordPress. The estates can be any accessible estates, since they all are published for the website. Therefore we should for example give a link to a random estate's detail page.

## Previous issues
The first time we bet on this, we left a placeholder title instead of using the estate's actual title. Additionally, the HTML did not look properly structured, for example with unneeded, empty `<div>`s.

![image](https://user-images.githubusercontent.com/90763364/197566787-f869232a-db4a-4eb5-a8b1-e5d0cf85ab5b.png)</div>

**Comment by dai-eastgate** [comment]
@jmaas-onoffice Could you please explain more specifically about requirement " The first time we bet on this, we left a placeholder title instead of using the estate's actual title".

**Comment by jmaas-onoffice** [comment]
I just meant that in [my comment](https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/331#discussioncomment-3749517) I used the link text "Beautiful home with great view". But that was just a placeholder. That should actually be the title of the estate that is linked.

**Comment by dai-eastgate** [comment]
@jmaas-onoffice If the title of the estate is empty. How should I use the link text?

**Comment by jmaas-onoffice** [comment]
Oh, good edge case! Should be rare, but how about we use a placeholder like "Example estate"? Please make it translatable.

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I fixed, you can watch video and give me feedback.


https://user-images.githubusercontent.com/106214469/203246297-a0f2bbfc-3013-4291-8908-8566e82fa473.mp4

**Comment by jmaas-onoffice** [comment]
@dai-eastgate The link text looks good, thanks! :)

I notice that there is no space between the paragraphs of the text above it. Is the HTML correct or is it like in the screenshot?

**Comment by dai-eastgate** [comment]
@jmaas-onoffice The html is correct in the screenshot, you can recheck.

![image](https://user-images.githubusercontent.com/106214469/203493729-98c3e79c-1173-48cc-b665-1812442cee74.png)

**Comment by jmaas-onoffice** [comment]
Could you use <p> for the paragraphs? Otherwise it looks good, thanks! :)
