### ISSUE TITLE
Allow clicking on the field name to add and remove fields

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#383]
Adding and removing a field from the field list is only possible when clicking the icon. Clicking on the label does not do anything, even though the mouse becomes a pointer.

![image](https://user-images.githubusercontent.com/90763364/204496347-da36492a-9321-412f-b6f2-a35255a8df5c.png)

Please also allow clicking on the field name to add and remove the fields.

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I fixed, you can watch video and give me feedback.

https://user-images.githubusercontent.com/106214469/205003165-03788e01-b7d7-4945-9d25-31fa26315bc4.mp4

**Comment by jmaas-onoffice** [comment]
@dai-eastgate That looks good, thanks!

Just for your information: During the cycle you can focus on the bets. These issues marked with "small change" are meant to be done during ramp-up. So it's all good, if all the bets are already done, but those are more important than these small changes. ;)
