### ISSUE TITLE
Unit lists' fields change order when saving

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#392]
The fields of unit lists change their order unexpectedly when saving.

1. Create a new unit list. Give it a name and save it.
2. Remember the first three fields and save the list without any changes.
3. Notice that they have changed places.
4. Save the list again.
5. Often, it switches between two orders, so the fields should now be back in their original place.

However, we want the field order to stay consisten between saves when the user did not change anything.

**Comment by hungnc89** [comment]
@jmaas-onoffice we were not able to reproduce the problem as you said, here is a video of our operations, you can watch and comment where we went wrong

https://user-images.githubusercontent.com/72601287/210027658-32eea461-c66d-44e6-b96d-1713daae4f50.mp4

**Comment by jmaas-onoffice** [comment]
You did everything right. Seems like you can't reproduce the problem.

Could you send me the site health info of the WordPress instance that you used to test this? Under "Tools > Site Health > Info" is a button for copying it. Then I could have a look to see if there are differences betwenn our test instances.

**Comment by dai-eastgate** [comment]
[message.txt](https://github.com/onOffice-Web-Org/oo-wp-plugin/files/10358071/message.txt)
@jmaas-onoffice Here is the site health info that you tell me to copy. You can check and tell me what difference is.
