### ISSUE TITLE
Newsletter field breaks form submission

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#397]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/390

<div type='discussions-op-text'>

<sup>Originally posted by **jmaas-onoffice** December 13, 2022</sup>
As described in #386, the newsletter field prevents forms from being sent.

Since [research is needed](https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/386#issuecomment-1340675421) to understand why this is happening, I propose to spend at most a week trying to fix this issue.

If the issue cannot be resolved in a week, please report what you learned and what you think would be necessary to understand and fix the problem.</div>

**Comment by jmaas-onoffice** [comment]
Looks good!

Out of curiosity: What was the cause for the problem? :)

**Comment by hungnc89** [comment]
@jmaas-onoffice When create address, data send has 'newsletter' field, it's not working, it should be 'newsletter_aktiv'.

**Comment by jmaas-onoffice** [comment]
Ah, that makes sense. Thanks! :)
