### ISSUE TITLE
Custom label should be used in estate search

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#418]
In https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/405 we added custom labels for estate lists.

However, when you make a field filterable and give it a custom label, that new label only shows up in the list, not in the search form.

![image](https://user-images.githubusercontent.com/90763364/211875793-e616da4e-6aa1-4649-8bbf-b733fc1cfa24.png)

The custom label should be applied everywhere, including in the search form.

**Comment by dai-eastgate** [comment]
@jmaas-onoffice  I fixed this bug, you can watch video and give me feedback

https://user-images.githubusercontent.com/106214469/212619491-d9279689-84f0-4564-9ed4-c1601c0af1dd.mp4

**Comment by jmaas-onoffice** [comment]
Looks good, thank you! :)
