### ISSUE TITLE
Document enterprise filters

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#421]
> Time-tracking ticket: T#3455431

## Users seem confused where to configure the filters
In estate lists, you can choose a filter from enterprise. Many users are confused about this, probably because they expect to change the filters in the plugin.

## Refer to enterprise documentation
We want to add a hint that these are enterprise filters and point users to the enterprise documentation that describes them.

![image](https://user-images.githubusercontent.com/90763364/212055171-b870bba6-c675-4bd0-845e-fa8332e8745b.png)

> Choose an estate filter from onOffice enterprise. [Learn more.](https://de.enterprisehilfe.onoffice.com/help_entries/property-filter/?lang=en)

**Comment by dai-eastgate** [comment]
@jmaas-onoffice You can watch video and give me feedback.

https://user-images.githubusercontent.com/106214469/213077995-ea16e6bb-3b5e-4406-9b3f-c8dd962b7af1.mp4
