### ISSUE TITLE
Custom labels not usable and not used in sort dropdown

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#426]
## Cannot save custom label
Commit https://github.com/onOffice-Web-Org/oo-wp-plugin/commit/01de67715425d81d870db33218986193b2f2ee75 introcudes an error, that when you try to customize an estate field's label, it does not save and you can't add custom labels for other languages.

The browser console shows this error:

```
onoffice-custom-form-label.js?ver=6.1.1:32 
        
       Uncaught TypeError: Cannot read properties of null (reading 'text')
    at onoffice-custom-form-label.js?ver=6.1.1:32:66
    at onoffice-custom-form-label.js?ver=6.1.1:45:11
    at NodeList.forEach (<anonymous>)
    at onOffice.custom_labels_input_converter (onoffice-custom-form-label.js?ver=6.1.1:14:160)
    at onoffice-custom-form-label.js?ver=6.1.1:113:10
```

## Custom label not used in sort dropdown
When I configure a list to be sorted by "User selection", the dropdown in the frontend does not use the custom label for the fields:

![image](https://user-images.githubusercontent.com/90763364/215453166-b1e64eb9-e92f-49a3-9060-fb1ad18deb2b.png)

**Comment by jmaas-onoffice** [comment]
I have reverted the commit, so that we can do a release. Once fixed, you'll need to reapply the commit.

**Comment by jmaas-onoffice** [comment]
We noticed another issue with the custom labels. I think it's easiest to fix both together, so I put them both in this issue.

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I fixed, you can watch video and give me feedback 

https://user-images.githubusercontent.com/106214469/215996657-d4e9d145-bd51-428d-868f-a40b4b3b1ece.mp4

**Comment by jmaas-onoffice** [comment]
Looks good, thank you!
