### ISSUE TITLE
Show quick actions in backend

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#437]
The quick actions in the menu bar are only visible in the frontend.

![image](https://user-images.githubusercontent.com/90763364/216092517-2d2b1131-a605-4e3a-a425-c9fc4aef9934.png)

We have decided that we want to also show them in the backend.

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I added the quick actions in menu bar in the backend. You can see and give me feedback
![image](https://user-images.githubusercontent.com/106214469/216230232-ac3faf7b-2a93-4936-b536-4aba1f3c2562.png)
