### ISSUE TITLE
Custom label doesn't work on first save in Similar Estate and Detail Estate

### ISSUE THREAD

**Issue by dai-eastgate** [onOffice-Web-Org/oo-wp-plugin#442]
When I fixed issue #426 I found another error: Custom label doesn't work on first save. This error occurs in both detail view and similar estate. I have recorded a video of the bug below. Do you want me to fix it in the next cycle or not? 

https://user-images.githubusercontent.com/106214469/217422881-d2caadf0-ca79-4eed-9219-5ab8adbf8815.mp4

**Comment by dai-eastgate** [comment]
@jmaas-onoffice
When I fix this issue https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/426
We discovered this issue
Please check and give me your opinion on this issue

**Comment by jmaas-onoffice** [comment]
Thanks for making this issue! We will decide if we do this in the next cycle or during ramp-up and tell you.

**Comment by jmaas-onoffice** [comment]
Do you have an estimate how long this would take to fix?

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I think we should do this bug in ramp-up.

**Comment by dai-eastgate** [comment]
I fixed this bug, you can watch the video and give me feedback.

https://user-images.githubusercontent.com/106214469/223335736-c50e769a-7c4f-49f6-b339-f7240af6cdc7.mp4

**Comment by fredericalpers** [comment]
Seems good to me! Seems good! I'll consult our devs on how to proceed from here.

**Comment by dai-eastgate** [comment]
Merged at https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/457
