### ISSUE TITLE
Rework introduction page

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#447]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/433

<div type='discussions-op-text'>

<sup>Originally posted by **jmaas-onoffice** January 27, 2023</sup>
> Time-tracking ticket: T#2865395 

## Current state

The plugin has a "welcome page" behind the first menu entry "onOffice".

![image](https://user-images.githubusercontent.com/90763364/215067697-fce2a8bb-a9f2-414e-bbbf-342024dba21b.png)

It is not translated and it does not link to the plugin's documentation website ([https://wpplugindoc.onoffice.de/](https://wpplugindoc.onoffice.de/)).

## Desired state

1. The menu entry should be renamed from "onOffice" to "Getting started".
2. The text should be made translatable (using the gettext methods, [https://make.wordpress.org/polyglots/handbook/plugin-theme-authors-guide/gettext/](https://make.wordpress.org/polyglots/handbook/plugin-theme-authors-guide/gettext/ "‌")) as a single block. We want to use Markdown (via Parsedown, which is already installed).
3. The content of the page should be as follows:

```
## Connect your website to onOffice enterprise

You are ready to integrate all your real estate into your website and create forms that send data into onOffice enterprise.

For help with setting up the plugin, read through our [setup tutorial](https://wp-plugin.onoffice.com/en/first-steps/).

The [documentation website](https://wp-plugin.onoffice.com/en/) also offers detailed explanations of the features. If you encounter a problem, you can send us a message using the [support form](https://wp-plugin.onoffice.com/en/support/).
```

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I reworked the introduction page, you can watch video and give me feedback 

https://user-images.githubusercontent.com/106214469/220032943-d2b10d8a-6865-4e88-82f7-f14dd33a61f8.mp4

**Comment by jmaas-onoffice** [comment]
@dai-eastgate That looks pretty good! Just two questions:

1. Why is there a gray block at the end of the text?
2. How did you do the German translation?

**Comment by dai-eastgate** [comment]
1. I see in the content you sent with ```, it has been changed by markdown to gray block. I will delete it.
![image](https://user-images.githubusercontent.com/106214469/220072679-78281ecc-ab9f-4ae5-be6d-040b9ec821a9.png)
2. "
"
msgstr ""
"## Website mit onOffice Enterprise verbinden\n"
"\n"
"Sie sind bereit, alle Ihre Immobilien in Ihre Website zu integrieren und Formulare zu erstellen, die Daten an onOffice Enterprise senden.\n"
"\n"
"Wenn Sie Hilfe beim Einrichten des Plugins benötigen, lesen Sie unser [Setup-Tutorial](https://wp-plugin.onoffice.com/en/first-steps/).\n"
"\n"
"Die [Dokumentations-Website](https://wp-plugin.onoffice.com/en/) bietet auch detaillierte Erläuterungen zu den Funktionen. Wenn Sie auf ein Problem stoßen, können Sie uns über das [Support-Formular](https ://wp-plugin.onoffice.com/en/support/).\n"
"
"
</code>

**Comment by jmaas-onoffice** [comment]
@dai-eastgate 

1. You're right, there was a mistake in the issue. I updated the issue. Thanks!
2. If you try to [translate a variable](https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/453/files#diff-e1e98a6fa366247696c3dc629473c878a32edcd04ce6002c17fedf41f302fc14R91), the WordPress translation platform will not pick up the text. So you can't have the text in another file, you need to put it as a literal into the translation function `__()`.

**Comment by dai-eastgate** [comment]
@jmaas-onoffice yes, For "translate a variable" I will check it again.

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I fixed, you can watch video and give me feedback 

https://user-images.githubusercontent.com/106214469/220278776-ec62f4f1-74e2-44fe-ac8f-4d10456fe534.mp4

**Comment by dai-eastgate** [comment]
@jmaas-onoffice Can you give me feedback so I can merge it into master.

**Comment by jmaas-onoffice** [comment]
@dai-eastgate It looked good. There was just a small change for the translation that I did, because it was more difficult to explain than do it.

I am going to merge the PR, thank you! :)
