### ISSUE TITLE
"breitengrad" leads to UnknownFieldException

### ISSUE THREAD

**Issue by jmaas-onoffice** [onOffice-Web-Org/oo-wp-plugin#450]
It seems #428 did not fix the issue completely. Therefore I reverted it for the release and here is some more information.

If the geo range search is active, on some estates the plugin fails with an UnknownFieldException, related to the "breitengrad" field.

![Webaufnahme_8-2-2023_153538_testinstanz-jmaa onofficeweb com (1)](https://user-images.githubusercontent.com/90763364/217759351-a116fc86-5f21-49ec-a7af-d7393f094683.jpeg)

```
[onOffice-Plugin] An error occured:
onOffice\WPlugin\Field\UnknownFieldException in /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Types/FieldsCollection.php:98
Stack trace:
#0 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/EstateList.php(493): onOffice\WPlugin\Types\FieldsCollection->getFieldByModuleAndName('estate', 'breitengrad')
#1 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/templates.dist/estate/default.php(111): onOffice\WPlugin\EstateList->getFieldLabel('breitengrad')
#2 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Template.php(118): include('/www/htdocs/w01...')
#3 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Template.php(82): onOffice\WPlugin\Template::getIncludeContents(NULL, '/www/htdocs/w01...', NULL)
#4 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeEstateList.php(137): onOffice\WPlugin\Template->render()
#5 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeEstate.php(94): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeEstateList->render(Array)
#6 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeEstate.php(69): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeEstate->buildReplacementString(Array)
#7 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/Controller/ContentFilter/ContentFilterShortCodeRegistrator.php(59): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeEstate->replaceShortCodes(Array)
#8 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/shortcodes.php(355): onOffice\WPlugin\Controller\ContentFilter\ContentFilterShortCodeRegistrator->onOffice\WPlugin\Controller\ContentFilter\{closure}(Array, '', 'oo_estate')
#9 [internal function]: do_shortcode_tag(Array)
#10 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/shortcodes.php(227): preg_replace_callback('/\\[(\\[?)(oo_est...', 'do_shortcode_ta...', '[oo_estate view...')
#11 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/class-wp-hook.php(308): do_shortcode('[oo_estate view...')
#12 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/plugin.php(205): WP_Hook->apply_filters('[oo_estate view...', Array)
#13 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/post-template.php(255): apply_filters('the_content', '<!-- wp:shortco...')
#14 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/themes/neve/inc/views/page_layout.php(29): the_content()
#15 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/class-wp-hook.php(308): Neve\Views\Page_Layout->render_page('')
#16 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#17 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#18 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/themes/neve/template-parts/content-page.php(9): do_action('neve_do_single_...')
#19 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/template.php(785): require('/www/htdocs/w01...')
#20 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/template.php(718): load_template('/www/htdocs/w01...', false, Array)
#21 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/general-template.php(204): locate_template(Array, true, false, Array)
#22 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-content/themes/neve/page.php(47): get_template_part('template-parts/...', 'page')
#23 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-includes/template-loader.php(106): include('/www/htdocs/w01...')
#24 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/wp-blog-header.php(19): require_once('/www/htdocs/w01...')
#25 /www/htdocs/w01bb2af/testinstanz-jmaa.onofficeweb.com/htdocs/index.php(17): require('/www/htdocs/w01...')
#26 {main}
```

 I could not understand why this does not happen for all estates. I suspect that the "breitengrad" (latitude) and "laengengrad" (longitude) fields are set, when enterprise understands the address and can add those coordinates. But it is unclear to me why some estates get coordinates, even though they have invalid addresses.

In any case, when activating the geo range search, the estate list should work properly.

**Comment by dai-eastgate** [comment]
@jmaas-onoffice I checked the code.
If "breitengrad" (latitude) and "laengengrad" is valid but the addresses is invalid then "breitengrad" (latitude) and "laengengrad" is set to 0.
Currently, we are not showing errors like yours. You can watch the video of me doing this debugging
If I disable this code, everything is displayed

https://user-images.githubusercontent.com/106214469/221498071-1f501e45-5038-4fb4-8b49-b486a7a11867.mp4

**Comment by jmaas-onoffice** [comment]
Thanks for the code.

So the problem does _not_ occur if

1. the virtual address is active, or
2. the address is not published, or
3. the street is empty.

It seems that the code resets the [coordinate fields](https://github.com/onOffice-Web-Org/oo-wp-plugin/blob/b445acae3e0172f7311ac0bdf3ae5b084a1131ac/plugin/ViewFieldModifier/EstateViewFieldModifierTypeEstateGeoBase.php#L76-L87) in those cases.

But that still means that if someone is sharing the real address and has filled out the street, that it breaks the plugin when the template requests the field's label. This is something that should be fixed.

**Comment by dai-eastgate** [comment]
Yes, I will check it again

**Comment by dai-eastgate** [comment]
I checked the case you said and found the Geo range search field did not give an error. If you share the correct address + the street field is not empty + Select yes in the Marketing > Share address as in the attached image, the coordinate field will display.
![450](https://user-images.githubusercontent.com/106214469/223038707-d7927c2c-7f9d-4a13-b532-09372a00f4aa.png)

**Comment by fredericalpers** [comment]
Seems good! I'll consult with our devs on how we will proceed from here.

**Comment by dai-eastgate** [comment]
I checked [#428](https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/428), =>  the issue completely.

https://user-images.githubusercontent.com/106214469/229972299-f7b64ee6-e8c6-4c6b-8bd1-106938117723.mp4


Maybe because you haven't entered the **"city"** field when you search by **"country".**

Because in the code that has checked the condition, when searching by **country**, you must enter  **"city"** field
![image](https://user-images.githubusercontent.com/106214469/229972677-b57967be-7fa3-4667-9197-16678778274d.png)


Pls check again.
I have reverted the code to pull request

**Comment by fredericalpers** [comment]
@dai-eastgate We are currently reviewing the issue and will give feedback latest next week. Since public holidays are coming up.

**Comment by dai-eastgate** [comment]
Merged at https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/480
