### ISSUE TITLE
Price on request

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#492]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/482

<div type='discussions-op-text'>

<sup>Originally posted by **fredericalpers** April  4, 2023</sup>
### Current state

Price on request function can currently not be used.

The actual property prices should not be displayed by default if "Price on request" is set to "Yes". At the moment, this is only possible via template adjustments.

Currently we have to add the field “preisAufAnfrage” into the $dontEcho and then later into an if-loop so the value “Preis auf Anfrage” will be displayed instead the actual price.

```
$dontEcho = array("objekttitel", "objektbeschreibung", "lage", "ausstatt_beschr", "vermarktungsart", "objektart", "nutzungsart", "regionaler_zusatz", "ort", "plz", "land", "vermarktungsstatus", "preisAufAnfrage");

if ($field == "kaufpreis" || $field == "warmmiete") {
	if ($currentEstate['preisAufAnfrage'] == 'Ja') {
		$value = esc_html('Preis auf Anfrage', 'oo_theme');
	}
}
```

### Desired state
If the “Price on request” Checkbox is ticked in onOffice enterprise the value should display “Preis auf Anfrage” in the frontend of the website instead of the actual price.
</div>

**Comment by dai-eastgate** [comment]
@fredericalpers I finished this issue, you can watch the video below and give me feedback

https://user-images.githubusercontent.com/106214469/232423097-399af341-547f-4290-bbbc-852d4f40323a.mp4

**Comment by yeneastgate** [comment]
@fredericalpers I finished this issue, you can watch the video below and give me feedback

https://user-images.githubusercontent.com/104892108/232424141-cd6caf4b-91e3-4fc5-90fb-b8f6251a7010.mp4

**Comment by fredericalpers** [comment]
@yeneastgate the basic rent does not seem to be included? From my experience, most real estate agents in Germany will use basic rent as the value displayed.

**Comment by dai-eastgate** [comment]
@fredericalpers 
Do you want to add any other types of prices? such as "Price, Rental income per month, Rent for parking space..."

Or only support for "kaufpreis, warmmiete, kaltmiete"

Please specify the all type prices Which you want to support the "price on request" feature.
Thanks!

**Comment by fredericalpers** [comment]
> @fredericalpers Do you want to add any other types of prices? such as "Price, Rental income per month, Rent for parking space..."
> 
> Or only support for "kaufpreis, warmmiete, kaltmiete"
> 
> Please specify the all type prices Which you want to support the "price on request" feature. Thanks!
> 
> I fixed for "basic rent" case. This demo video
> 
>  price_on_request.mp4

I'm contacting our IT Department to figure out which fields are connected to the Checkbox and will update you, hopefully shortly.

**Comment by fredericalpers** [comment]
@dai-eastgate @yeneastgate 

The following values are supposed to be overwritten with "Price on request" if activated:

- Kaufpreis fieldname = kaufpreis
- Erbpacht fieldname = erbpacht
- Netto Kaltmiete fieldname = nettokaltmiete
- Warmmiete fieldname = warmmiete
- Pacht fieldname = pacht
- Kaltmiete fieldname = kaltmiete
- Pauschalmiete fieldname = miete_pauschal
- Saisonmiete pauschal fieldname = saisonmiete
- Wochenmietpreis brutto fieldname = wochmietbto
- Kaufpreis pro qm fieldname = kaufpreis_pro_qm
- Mietpreis pro qm fieldname = mietpreis_pro_qm

**Comment by yennt89** [comment]
@fredericalpers Thanks, I will fix it.

**Comment by yeneastgate** [comment]
@fredericalpers I updated. You can watch the video below. 

https://user-images.githubusercontent.com/104892108/233900524-cde77606-ed3f-4d21-bc06-cb823ee31d0b.mp4

**Comment by fredericalpers** [comment]
> @fredericalpers I updated. You can watch the video below.
> 
>  price_on_request.mp4

thank  you! looks good to me :)

**Comment by fredericalpers** [comment]
@yeneastgate  after discussing it with my colleagues, we would like to implement further changes.

- the field “preisAufAnfrage” should not be selectable in the field list anymore
- it should be a checkbox below “Immobilienstatus anzeigen”(see preisAufAnfrage-layout and preisAufAnfrage-layout-detail screenshots)
- The field / checkbox doesn't need to be filterable
- make sure backwards compatibility is given. The checkbox should not be checked by default. In cases where customers use the field in the field list and its being deleted with the new patch, the checkbox for "preisAufAnfrage" in WP Backend needs to be checked, so the actualy prices are not shown.

![preisAufAnfrage-layout](https://user-images.githubusercontent.com/88546396/235849792-3e164da7-b09a-49f9-ae16-98cd9e737871.jpg)
![preisAufAnfrage-layout-detail](https://user-images.githubusercontent.com/88546396/235849795-18fd0173-d595-4b75-9212-bee4b3200d7d.jpg)
![preisAufAnfrage-old](https://user-images.githubusercontent.com/88546396/235849796-311dfd5b-55cb-4a4e-ad82-4536474e3bd4.jpg)

**Comment by yeneastgate** [comment]
@fredericalpers yes, I will implement it.

**Comment by yeneastgate** [comment]
Hi @fredericalpers 
I would like to confirm a point. 
In the frontend, the "detail" page also displays the "similar estates list". However, we currently only apply the "Price on request" feature for the "detail" page, while the "similar estates list" still shows the price. 
Therefore, do you want to use the "price-on-request" feature for the similar estate as well?

**Comment by fredericalpers** [comment]
> @fredericalpers I would like to confirm a point. In the frontend, the "detail" page also displays the "similar estates list". However, we currently only apply the "Price on request" feature for the "detail" page, while the "similar estates list" still shows the actual price. Therefore, do you want to use the "price-on-request" feature for the similar estate as well?

@yeneastgate yes the similar estates also should habe the price on request feature.

**Comment by yeneastgate** [comment]
@fredericalpers I modified the "Price on request" function as requested. Please take a look at the videos below and tell me your opinion. 
https://files.fm/u/drz2t95kn
