### ISSUE TITLE
New release = old bug again

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#496]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/495

<div type='discussions-op-text'>

<sup>Originally posted by **fredericalpers** April 11, 2023</sup>
After releasing the new Plugin Version we encountered an old bug again.

In enterprise deactivated fields will lead to critical error. </div>

**Comment by dai-eastgate** [comment]
> @dai-eastgate Please try to squeeze this in so we can release a Hotfix. If I remember we had this fixed before by "skipping" the deactivated fields.

I will check and fix it

**Comment by dai-eastgate** [comment]
@fredericalpers Can you be more specific about where the error occurs?

**Comment by fredericalpers** [comment]
> @fredericalpers Can you be more specific about where the error occurs?

In v4.10 of the plugin, in enterprise all deactivated fields will cause an critial error in WordPress when used in a property list. See the attachment below:

![deactived](https://user-images.githubusercontent.com/88546396/231159575-3ede6287-686c-4251-a73b-56a2ff5212e6.PNG)

**Comment by fredericalpers** [comment]
Perfect, thank you :)

**Comment by dai-eastgate** [comment]
yes, I will check it now

**Comment by yennt89** [comment]
@andernath @fredericalpers I fixed it.
This is demo video, pls check again

https://user-images.githubusercontent.com/61687197/231768098-df8bbb4c-19aa-44cd-9bd5-fd4836ae412e.MP4

**Comment by fredericalpers** [comment]
> 

Thank you! We will check again and give our feedback
