### ISSUE TITLE
Clearing the onOffice cache

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#504]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/483

<div type='discussions-op-text'>

<sup>Originally posted by **fredericalpers** April  4, 2023</sup>
### Current state
After clearing the cache there is no success message that the cache was actually cleared.

### Desired state
After clearing the cache there should be a success message. See attached screenshots. (success-message-ger.jpg) and success-message-en.jpg)

E.g.

![success-message-en](https://user-images.githubusercontent.com/88546396/229795847-609d4b6e-3fc5-41b2-b87c-cc8ebb6deccc.jpg)
![success-message-ger](https://user-images.githubusercontent.com/88546396/229795852-97123da3-d517-4bc2-a772-bf16a345c683.jpg)
</div>

**Comment by dai-eastgate** [comment]
@fredericalpers I added a success massage when clearing the cache. You can watch the video below and give me your feedback.

https://user-images.githubusercontent.com/106214469/234788163-9ae9d121-ecf0-48ff-80d7-de57cf42645a.mp4

**Comment by fredericalpers** [comment]
Thank you! Looks good to me.

**Comment by dai-eastgate** [comment]
merged at pull request #509
