### ISSUE TITLE
Saving lists or forms without a name

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#527]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/508

<div type='discussions-op-text'>

<sup>Originally posted by **fredericalpers** April 25, 2023</sup>
### Current state

When saving lists or forms without a name, the error message says: There was a problem saving the list. Please make sure the name of the list is unique.

"Immolisten DE: An error occurred while saving the view. Please make sure that no other view with this name exists, even if it has a different type." / "Immolisten DE: Beim Speichern der Ansicht ist ein Fehler aufgetreten. Bitte stelle sicher, dass keine andere Ansicht mit diesem Namen existiert, auch wenn sie einen anderen Typen hat." 

"Forms DE: An error occurred while saving the form. Please check if the form name is unique." / "Formulare DE: Es ist ein Fehler beim Speichern des Formulars aufgetreten. Bitte prüfe, ob der Formularname eindeutig ist."

### Desired state

It should say: "There was a problem saving the list. The Name field cannot be empty" / "Beim Speichern der Liste ist ein Problem aufgetreten. Das Feld Name kann nicht leer sein"
</div>

**Comment by fredericalpers** [comment]
@yeneastgate as mentioned in the meeting earlier, here's one of the issues for ramp up period.

**Comment by yeneastgate** [comment]
@fredericalpers yes, i will implement it

**Comment by dai-eastgate** [comment]
@fredericalpers
 I want to confirm with you:
For forms:
Do I need to change the message: "There was a problem saving the list. The Name field cannot be empty" => "There was a problem saving the form. The Name field cannot be empty" message?

For Addresses:
Do I also need to update the message "There was a problem saving the view. Please make sure the name of the view is unique, even across all estate list types." => "There was a problem saving the address. The Name field cannot be empty"?

Please let me know soon.

**Comment by fredericalpers** [comment]
> @fredericalpers I would like to confirm with you: For forms: Do I need to change the message: "There was a problem saving the list. The Name field cannot be empty" => "There was a problem saving the form. The Name field cannot be empty"?
> 
> For Addresses: Do I also need to update the message "There was a problem saving the view. Please make sure the name of the view is unique, even across all estate list types." => "There was a problem saving the address. The Name field cannot be empty"?
> 
> Please let me know soon.

Thank you for your feedback. Yes please go ahead and change it. :)

**Comment by yeneastgate** [comment]
@fredericalpers I changed the error message as discussed above, please take a look at the attached video and give me your feedback. Thanks!

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/d5db3631-e202-445b-8b9b-7e1dfbd129d6

**Comment by fredericalpers** [comment]
> @fredericalpers I changed the error message as discussed above, please take a look at the attached video and give me your feedback. Thanks!
> 
>  34981.mp4

looks good to me! thank you :)
