### ISSUE TITLE
Edit list view

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#529]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/528

<div type='discussions-op-text'>

<sup>Originally posted by **fredericalpers** May 24, 2023</sup>
### Current state

In the upper right corner it shows "Customize View" where you can supposedly switch the layout between 1 column and 2 columns. This does not work.

### Desired state

“Customize View” has to be removed. Since it doesn’t work and there already are enough problems with the layout of the backend.

![customize-view](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/70724b3a-02a2-4f2a-a94e-cd199b72e338)
</div>

**Comment by yeneastgate** [comment]
@fredericalpers yes, i will implement it

**Comment by dai-eastgate** [comment]
@fredericalpers I have questions need to confirm with you.
1. Do you want me to remove only the "layout column" or do you want me to remove the whole "screen option"?
2. Do you want me to only remove in "Edit List View" or do you want me to remove in all other views (Detail, Similar, Unit List, Form)

**Comment by fredericalpers** [comment]
> @fredericalpers I have checked this issue and found that the “Customize View” also is shown in other pages such as: Detail estate, Similar estate and Forms. And this also does not work. So, do you also want to remove the “Customize View” from these pages? Please let me know your opinion. Thanks.

yes, please remove it from all pages, where it does not work. Thank you.

**Comment by dai-eastgate** [comment]
@fredericalpers I removed the "Customize View" from pages that it does not work. Please take a look at the video below and let me know your opinion. Thanks 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/f0c13abb-3b1e-422a-bd72-57305f916f10

**Comment by fredericalpers** [comment]
> @fredericalpers I removed the "Customize View" from pages that it does not work. Please take a look at the video below and let me know your opinion. Thanks
> 
>  34982.mp4

Thank you for the quick fix :)
