### ISSUE TITLE
Similar estates only allow title picture

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#538]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/485

<div type='discussions-op-text'>

<sup>Originally posted by **fredericalpers** April  4, 2023</sup>
### Current state
For similar estates only "title picture" is supported.

e.g. a customer has uploaded a title picture in onOffice enterprise which is only supposed to be used for other real estate portals such as the german portal: Immobilienscout24. It is only possible to chose one "title picture" in onOffice enterprise. In this case the plugin can not use the picture on the website.

Therefore the similar estate card in the estate detail page does not have a image displayed on their website.

### Desired state

All other image types should be supported and able to be used as they are in the estate detail page. Please make them selectable as in the detail page “picture types”.

See attachments (detailpage_pictures.png) and (similarestates_only_titlepic.png)

![detailpage_pictures](https://user-images.githubusercontent.com/88546396/229799618-4db07b03-9f2f-42e9-ab0d-feef4be70f8d.jpg)
![similarestates_only_titlepic](https://user-images.githubusercontent.com/88546396/229799617-cb1ec62d-806a-4765-9ebc-5d729696208e.jpg)

</div>

**Comment by yeneastgate** [comment]
Hi @fredericalpers,
I would like to confirm with you:  What is the default status of the "photo types" section of the similar estate (for both new and old users)? Do you want to activate all options or only one option? Please let me know your opinion about this. Thanks!
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/6cb1cbf4-9af0-45d3-8715-d82b0d1f9486)

**Comment by fredericalpers** [comment]
> Hi @fredericalpers, I would like to confirm with you: What is the default status of the "photo types" section of the similar estate (for both new and old users)? Do you want to activate all options or only one option? Please let me know your opinion about this. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/104892108/246740616-4b1ebdd6-5703-432b-be8c-596fb720d437.png)

@yeneastgate Sorry for the late reply. Please only check >cover photo< by default since these are the pictures used before. The other ones are a new feature.
