### ISSUE TITLE
Ownerform - GDPR Checkbox

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#542]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/537

<div type='discussions-op-text'>

<sup>Originally posted by **fredericalpers** May 26, 2023</sup>
### Current state

In the incoming mail generated by the owner form, the GDPR checkbox is only transmitted with ": 1".

![ownerform-gdpr-1](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/1311ad0e-0471-4715-acc6-8bc5cd0e53ad)

### Desired state
As with the other forms, the output should not only transfer the value, but also display the text in the mail.

</div>

**Comment by dai-eastgate** [comment]
@fredericalpers 
I check the code and found the "GDPR checkbox" feature is working like this in the "Contact Form". See the attached image.
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/971784be-4b33-42e6-8b25-c8b2141e3148)

In "Interest Form" and "Owner Form" are working like this. See the attached image.
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/dd98a2f7-97f2-465a-a294-2fa5771f39cc)

So, I want to confirm with you that:
1. Do you want me to fix it in the "Interest Form" and "Owner Form" as well, or just fix it in the "Owner Form"?
2. Is this feature the same as the contact form?
Please, let me know your opinion about this. Thanks!

**Comment by fredericalpers** [comment]
@dai-eastgate The feature is the same, therefore should work the same in all forms and display the text in the e-mail. Please go ahead and fix it for all forms. Thank you :)

**Comment by yeneastgate** [comment]
@fredericalpers I fixed the "GDPR checkbox" for Owner Form and Interest Form as discussed above. Please take a look at the attached video and let me know your opinion. Thanks! 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/5e9e7a1a-849d-40e8-9443-69391a39c85f

**Comment by fredericalpers** [comment]
> @fredericalpers I fixed the "GDPR checkbox" for Owner Form and Interest Form as discussed above. Please take a look at the attached video and let me know your opinion. Thanks!
> 
>  GDPR_checkbox_active.mp4

@yeneastgate thank you! :) now it should be more clear for the clients that the customers actually agreed to the privacy policy etc.
