### ISSUE TITLE
onoffice-style.css with child theme

### ISSUE THREAD

**Issue by onOffice-Web** [onOffice-Web-Org/oo-wp-plugin#548]
### Discussed in https://github.com/onOffice-Web-Org/oo-wp-plugin/discussions/533

<div type='discussions-op-text'>

<sup>Originally posted by **fredericalpers** May 26, 2023</sup>
### Current state

The onoffice-style.css does not work properly when using a child theme. The plugin recognizes that the file is in the child theme, but then includes it with the URL of the parent theme.

### Desired state
The URL must be adjusted so that the onoffice-style.css are recognized and included correctly in any possible case.
</div>

**Comment by yeneastgate** [comment]
Hi @fredericalpers,
I fixed this issue, please take a look at my attached video and let me know your opinion about this. Thanks!
https://files.fm/f/qpudq94ta

**Comment by onOffice-Web** [comment]
@yeneastgate  Looks good to me! Thank you :)
