### ISSUE TITLE
Plugin can not set supervisor in address record

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#553]
### Current state

When creating address records from property requests, the plugin seems to always set the API user as the supervisor when creating the customer address record. Even if a supervisor is already added to the property prior to the property being published. See screenshot below.

### Desired state
If there is a supervisor added to the property, the customers address record which is being created should also have the supervisor added instead of the API User.

![supervisor-address-record](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/ff2abcaf-6a4b-4cac-9532-7e50fc17db9a)

**Comment by yeneastgate** [comment]
Hi @fredericalpers, I have a question about this issue.
When creating an interest form, do you want every position in the "supervisor" fields like the image below to have the same ID?
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/76302a20-a1ad-4085-8a3b-635923b68dc4)
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/97438bd6-2b7f-44da-9f25-4a8c310e695c)
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/8e9db4ba-6721-430d-a99f-75dab1f80d24)

**Comment by fredericalpers** [comment]
@yeneastgate this is only to be implemented for the inquiry formss on the detail page for now. Thank you :)

**Comment by yeneastgate** [comment]
@fredericalpers We found the solution and will implement it.

**Comment by dai-eastgate** [comment]
@fredericalpers I fixed it, please look at my video and let me know your opinion. Thanks

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/7d49c080-f3b5-40bb-a00a-4838d811751c

**Comment by onOffice-Web** [comment]
> @fredericalpers I fixed it, please look at my video and let me know your opinion. Thanks
> 
>  supervisor.mp4

Seems to be working correctly now! Thank you :)
