### ISSUE TITLE
“Fax” is not output

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#559]
### Current state
Even if a “fax” number is added to the contact persons detail and the field is added to the field list in WordPress, the fax number is not displayed in the frontend.

### Desired state
The fax number should be displayed, when its added to the contact persons details.

![fax-enterprise](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/086add5f-2d63-491a-8d44-f6e42c8cb60a)
![fax-plugin](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/d23e1d54-4dd3-457e-b98d-6c2219759147)
![fax-frontend](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/07f6999c-98ea-4157-94e9-85b5e0ae9f80)

**Comment by yeneastgate** [comment]
Hi @fredericalpers, I checked in the enterprise, fax number field has 3 types: default, private, and business. Do you want me to show all 3 types or just show the default type? Please let me know your opinion about this. Thanks!

![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/72339540-32c0-4e5f-8bd3-3bbf732306e4)

**Comment by fredericalpers** [comment]
> Hi @fredericalpers, I checked in the enterprise, fax number field has 3 types: default, private, and business. Do you want me to show all 3 types or just show the default type? Please let me know your opinion about this. Thanks!
> 
> ![image](https://user-images.githubusercontent.com/104892108/247048278-72339540-32c0-4e5f-8bd3-3bbf732306e4.png)

@yeneastgate There are two fields that can be used in the plugin. "All fax numbers [fax]" which is supposed to display all fax numbers.

"fax numbers [Telefax1]" which seems to be working should only display the selected one.

**Comment by yeneastgate** [comment]
> @yeneastgate There are two fields that can be used in the plugin. "All fax numbers [fax]" which is supposed to display all fax numbers.
> 
> "fax numbers [Telefax1]" which seems to be working should only display the selected one.

I got it, thanks!

**Comment by yeneastgate** [comment]
@fredericalpers I fixed this issue, please take a look at my video and let me know your opinion. 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/be5c49b5-59d7-430d-9889-499bd331720f

**Comment by fredericalpers** [comment]
@yeneastgate thank you for the quick fix :)
