### ISSUE TITLE
SEO Title and description

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#577]
### Current state

Currently we have the setting for Title and description to be filled out automatically using the information that is shown from the property. The number of characters / pixels are not limited, so they titles / descriptions will be cut off in google search results.

### Desired state

The title and description should have limited characters / pixels.
Title = approx. 554px (60 characters)
Description = approx. 990px (150 characters)

![title-description-current](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/9f3c33ce-4bcd-403c-a308-390fd55701a2)

**Comment by dai-eastgate** [comment]
@fredericalpers  The title and description have limited characters. Please watch video demo: https://files.fm/u/sxmf6bbac

**Comment by dai-eastgate** [comment]
@fredericalpers The title and description have limited characters. Please check video evidence https://files.fm/u/sxmf6bbac

**Comment by fredericalpers** [comment]
@dai-eastgate thank you!
