### ISSUE TITLE
Plugin Backend Design Adjustments

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#581]
### Current state

Currently the input fields, dropdowns and info messages are all over the place.

### Desired state
The inputs, dropdowns and info messages should be consistent in width and design. Please try to get rid of floats and use flexbox or grid. Add a appropriate padding. See the following screenshots.

![plugin-backend-adjustments](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/883b0e72-65ac-412e-9458-3d58e5b58f19)
![plugin-backend-adjustments-2](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/336dd1bb-6985-48c9-af6b-31bc29797701)
![plugin-backend-adjustments-2-1](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/c98e8bb5-f319-4542-94ba-4153119c4814)

**Comment by dai-eastgate** [comment]
@fredericalpers: This is an example of a CSS block I have modified. Please review the image below and confirm. If approved, I will apply the same modifications to other blocks. 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/89d504ea-61f8-4e70-a6ed-f91d07f05c4a)

**Comment by fredericalpers** [comment]
@dai-eastgate sorry for the late reply. yes this is the modifications I was hoping for! thank you :) see the images attached below for more information. Please go ahead and make sure that all info messages / hints are the same style. Preferably left aligned and a little margin (e.g. margin-bottom: 1.5rem) to the next item following below, so we can assure that by following the law of proximity the correct "objects" will be grouped together.

![info-messages](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/08248755-9033-4ada-9044-de86a76c2ed2)

**Comment by fredericalpers** [comment]
@dai-eastgate looks much better, thank you! :)
