### ISSUE TITLE
Sorting properties by property number (ImmoNr)

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#582]
### Current state

Currently if the properties are sorted by their property number (descending) only properties until number 999 will be sorted correctly. Properties with numbers over 1000 will be incorrectly added to the start. 

E.g. if sorted by property number (descending) it currently displays as the following:

999, 998, 997, ..., 200, ..., 1000, 1001, 1002

### Desired state

The properties should be sorted correctly. 

E.g. if sorted by property number (descending) it should be the following:

1003, 1002, 1001, 1000, 999, 998, 997, ...

![prop_no-descending](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/a58f77b7-f460-4ffb-b4b9-b631e0823dba)

![immoNR-bug-(1)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/71a92c34-ce15-4e9d-a349-7fe6d004c3ce)

**Comment by dai-eastgate** [comment]
@fredericalpers 
I have researched, implemented, and found the following issues:
- I have set sort ascending by propno in the Backend
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/53e222c6-fc38-42c3-8222-89a4a23a32e7)

- On the frontend side after I send the request param and use read estate API the estate data is returned as follows
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/c4b8671f-bca5-46c3-b264-0e083e8b3ee5)

- I tried sorting by propNo on the enterprise and data is sorting according to the API response

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/85fa17e3-ac7e-47d1-82c0-66c914f0d31c

So the current reason is that the API is responding in the wrong estate order.
Please check with your IT about these problems and let us know your opinion. Thanks.

**Comment by fredericalpers** [comment]
@dai-eastgate the feedback from the IT Department: "property number works as intended, since its string. the property numbers can contain letters as well." Therefore I will close this issue. I will recommend the customer to sort by "DatensatzNR" or set up a new "number field" for sorting. 

Thank you for your effort.
