### ISSUE TITLE
Price on request and seasonal rent (Saisonmiete)

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#584]
### Current state
Seasonal rent is added to the field list
Price on request is enabled for the given property

For the marketing types "Miete", "Pacht" and "Erbpacht", the price on request for "Saisonmiete"(seasonal rent) is always displayed in the property list (even if the value in onOffice enterprise is actually empty).

### Desired state
Seasonal rent should not be displayed if the value in enterprise is empty.

![saisonmiete_por](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/1d96a86c-4414-486d-8a91-c3bc3f491df4)

**Comment by fredericalpers** [comment]
As discussed in our meeting today (2023-07-05) I moved this issues to investigate and resolve into this milestone if possible.

**Comment by dai-eastgate** [comment]
> As discussed in our meeting today (2023-07-05) I moved this issues to investigate and resolve into this milestone if possible.

I will investigate and let you know as soon as possible

**Comment by yeneastgate** [comment]
Hi @fredericalpers, 
After checking, I found that there was a code that  covered the case "Seasonal rent do not be displayed if the value in the enterprise is empty."
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/0bf29cd8-cfba-4a3e-8cf0-4b7dfa7d2add)

We found that the cause may be that you have not cleared the API cache. Please watch the video for a better understanding.

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/ef1d2888-c193-440c-a645-f2bec9552df4

**Comment by fredericalpers** [comment]
@yeneastgate weird 😄  we tested it with 2 people and had the same problem. but it seems to be fixed now. thank you 👍
