### ISSUE TITLE
PDF Download in property lists

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#590]
### Current state
Currently it is possible to set a pdf download for the property list. See attached screenshot. This function does not work and should not exist in the property lists.

### Desired state
It has to be removed from property lists and should only be available in detail pages.

![property-list-pdf](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/bc392a75-be01-4951-9345-0a12cdd6f285)

**Comment by fredericalpers** [comment]
@dai-eastgate @yeneastgate please let me know if this will still fit in the current cycle/milestone or if I should move it to v4.16

**Comment by dai-eastgate** [comment]
> It has to be removed from property lists and should only be available in detail pages.

I will check and let you know as soon as possible

**Comment by dai-eastgate** [comment]
Hi @fredericalpers. After checking I found the following:
1. "PDF download" feature exists in 3 positions: Estate List, Detail View, and Unit Lists.

2. I set the shortcode of the unit list as this document (https://wp-plugin.onoffice.com/en/advanced-features/unit-lists/) and found it is working the same as the detail view (The fields displayed on the "Units" page are the fields configured in the "detail view"). 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/01908885-461a-4f1b-be90-2e19a201d3fa)

And if I put the shortcode like the attached image, the "Units" Page is showing like this. Please confirm for me how the "unit list" works properly.
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/f7fe4cce-75b3-4898-8f8a-e6434be3114c)

3. One more point, is you want me to remove the "PDF Download" feature in Estate List only or do you want to delete the unit list as well?
Please, let me know your opinion about this. Thanks!

**Comment by onOffice-Web** [comment]
@dai-eastgate Unit lists are currently a little confusing to use. They are just a addition to the detail page. We are already working on how to better implement them. More about that in the future. 

Please remove it from both the property list, as well as the unit list. Thank you. :)

**Comment by dai-eastgate** [comment]
> @dai-eastgate Unit lists are currently a little confusing to use. They are just a addition to the detail page. We are already working on how to better implement them. More about that in the future.
> 
> Please remove it from both the property list, as well as the unit list. Thank you. :)

I need 2 days to implement and test it. Thanks!

**Comment by dai-eastgate** [comment]
@fredericalpers For this issue, we would like to move it to the next cycle, as we are completing two issues: 553 & 562.

**Comment by yeneastgate** [comment]
Hi, @fredericalpers I finished implementing and testing this issue. Please take a look at my attached video and let me know your opinion. Thanks!

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/f2eb52c4-f924-454a-97c5-2d84ac8ce0a8

**Comment by fredericalpers** [comment]
@yeneastgate looks good to me, thank you :)
