### ISSUE TITLE
Urgent: Price on request Bug

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#602]
### Current state ###

After the release of v4.12 we unfortunately found a bug. If the field price on request is deactivated in onOffice enterprise it'll cause an critical error on the detail page tab and similar estate tab in the wordpress backend.

Old PR:  #498 

### Desired state ###

There has to be a query that makes sure that the field is activated in onOffice enterprise.

<details><summary>Screenshot Critical error</summary>
<p>

![critical-error](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/49e54d8d-3774-419d-8efd-29c57144035c)

</p>
</details>

**Comment by fredericalpers** [comment]
@yeneastgate @dai-eastgate

**Comment by andernath** [comment]
I guess we need a check of $pFieldsCollection->removeFieldByModuleAndName(onOfficeSDK::MODULE_ESTATE, 'preisAufAnfrage'); in AdminPageSimilarEstates.php and AdminPageEstateDetail.php

**Comment by dai-eastgate** [comment]
@fredericalpers @andernath We will check and fix it.

**Comment by yeneastgate** [comment]
@fredericalpers @andernath I fixed this bug. Please watch the attached video and let me know your opinions. Thanks!

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/c187379f-7a82-4e61-99e1-d21b679e4a2d
