### ISSUE TITLE
Custom label on detail pages

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#616]
### Current state

Currently some of the custom labels are not displayed correctly, instead the hardcoded text from the templates are displayed. Most of our customers have no to little experience modifying templates and struggle to do so.

### Desired state

The custom labels should be displayed correctly for all fields on property detail pages instead of always displaying the hardcoded text which can negatively impact the clarity and professionalism of the website.

![custom-label-detailpage](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/1805d484-dcdd-4c28-8ddf-1c23b0ef82f1)

**Comment by dai-eastgate** [comment]
@fredericalpers I found the solution and will implement it, I need 2 hours to fix and test it.
Note: I think you also know the implementation of this feature, the users must copy and overwrite the current template. Although this is a must. But I still want to remind us to have an overview of the task.

**Comment by fredericalpers** [comment]
@dai-eastgate yes, already existing templates will have to be modified by our customers to implement the fix. Going forward it would be good to make it as easy as possible for our customers hence the implementation for all custom label. Thank you for the reminder :)

**Comment by dai-eastgate** [comment]
@fredericalpers I fixed it. Please watch my video demo and let me know your opinion. Thanks!

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/0c83a2c5-5b91-466e-b3a6-e31f25caf36a

**Comment by fredericalpers** [comment]
@dai-eastgate thank you, our customers will be happy about that :)
