### ISSUE TITLE
Ownerform: Array list can not be sent

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#623]
### Current state

In the case of owner forms, contat data and property data are sent. At the moment it is not possible to send fields with multi selects.

The following warning is displayed:
```
Warning: ucfirst() expects parameter 1 to be string, array given in /www/htdocs/w01bee5f/w3pm.onofficeweb.com/htdocs/wp-content/plugins/onoffice-for-wp-websites/plugin/FormPostOwner.php on line 238
``` 

ucfist() only accepts strings. For one customer, this even led to a critical error and he could not send the form at all.

E.g.:
Add "Heating type" or "Combustion" as a field to the form. Fill in the form with multi-selects and submit.

### Desired state
Arrays should also be sent and should be displayed in the e-mail in comma-separated format.
The data should also be transferred correctly to onOffice enterprise.

**Comment by dai-eastgate** [comment]
@fredericalpers I need 3 days to fix and test it. Thanks!

**Comment by dai-eastgate** [comment]
@fredericalpers I fixed this bug, please take a look at my demo video and let me know your opinion about this. Thanks!
https://files.fm/u/xvd8fkdpcd

**Comment by fredericalpers** [comment]
@dai-eastgate looks good to me! thank you :) is this ready to be marked as in review then?

**Comment by dai-eastgate** [comment]
> @dai-eastgate looks good to me! thank you :) is this ready to be marked as in review then?

@fredericalpers yes, it's ready to be marked as in review
