### ISSUE TITLE
Screen options in property list overview and form overview

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#632]
# Current state
In the property list overview and forms overview, there is the option to edit the lists with the WordPress option "Screen Options". You can show and hide filters, show status, type of list and shortcode.

Besides the number of items per page setting, these screen options do not work properly. See Screenshots below.

(1) Column "Shortcode" is deselected, the "apply" button has not been clicked yet.
 
![no-shortcode-before-applying](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/6be567c7-c5cc-4ec1-9eca-8e0be270914c)

(2) Apply button has been clicked and the column "Shortcode" is still deselected, but the column in the table below will show again. 

![no-shortcode-after-applying](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/b5b2952b-da9c-4860-9eca-3585f2ac9ba8)

# Desired state
It should be possible to adjust the property list overview and form overview and the settings should be correctly applied after saving.

**Comment by yeneastgate** [comment]
@fredericalpers 
After checking, I see the "Screen option" feature in the "Addresses overview screens" is also not working properly.
=> Do you want me to fix the "Screen option" feature on this screen?
Note: Currently, in the "List View screen", the "show status" column is not displayed even though there is a "show status" checkbox in "screen options". Would you like me to display it in List View?
By the way, I need a day to fix and test this issue. Thanks!

**Comment by yeneastgate** [comment]
> To be honest, I don't even know what the "Show status" checkbox is supposed to be for. Please remove it.

=> I will remove the "Show status" checkbox 



> I don't think it's necessary to display the type of list here, since its only one possible type. If possible please remove the checkbox here.

=> OK, I will remove the "Type of list" checkbox

**Comment by yeneastgate** [comment]
@fredericalpers I have fixed the errors according to the following list
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/cc09e1c5-41a4-4afd-8cfd-3965f443ee39)

Please review the code and test it, thanks! Please watch my demo video.

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/1ac1799e-c17a-40bc-95cb-3041fd2a5a0e
