### ISSUE TITLE
Additional geographical information - "regionaler_zusatz" in email

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#633]
# Current state
Additional geographical information (regionaler_zusatz) is listed as a database key in the email and is therefore not readable for the email recipient.

If a search request is sent in which additional geographical information is selected, then the selected additional geographical information appears as e.g. "openGeoDb_Region_1113425" instead of "Aachen".

![additional-geo-info](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/cf171234-7f20-4298-bdaf-f3585b479768)

# Desired state
While the database key in the attached XML file is correct and needed, the additional geographical information (regionaler_zusatz) should be listed in plain text in the email so that the recipient is able to understand this at a glance.

**Comment by dai-eastgate** [comment]
@fredericalpers It takes me 2 days to fix and test. Thanks!

**Comment by dai-eastgate** [comment]
@fredericalpers While implementing, I see:
- There are fields with other types such as (boolean, multiselect, singleselect,..), are also displaying "value" instead of "label" like the "regionaler_zusatz" field.
=> Do you want me to also fix those error types?

**Comment by fredericalpers** [comment]
@dai-eastgate do you have a list of those fields?

**Comment by dai-eastgate** [comment]
> @dai-eastgate do you have a list of those fields?

Here is the list:
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/c05ee073-3761-4f60-8055-8b6acbefa2b8)

**Comment by fredericalpers** [comment]
@dai-eastgate I think for some of those fields it's necessary to use the value instead of the label. Let me discuss this with my colleagues one more time before further changes. I'll let you know asap :)

**Comment by fredericalpers** [comment]
@dai-eastgate please go ahead and implement the usage of the label instead of value, thank you :)

**Comment by dai-eastgate** [comment]
> @dai-eastgate please go ahead and implement the usage of the label instead of value, thank you :)

I got it. Thanks!

**Comment by dai-eastgate** [comment]
> @fredericalpers While implementing, I see:
> 
> * There are fields with other types such as (boolean, multiselect, singleselect,..), are also displaying "value" instead of "label" like the "regionaler_zusatz" field.
>   => Do you want me to also fix those error types?

I fixed this. Please take a look at my video demo and let me know your opinions. Thanks!


https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/9356f805-0b80-451f-bf10-156ccd6add6f

**Comment by fredericalpers** [comment]
@dai-eastgate seems good to me! thank you for the quick adjustments. :) Can I label this as "in review"?

**Comment by dai-eastgate** [comment]
> @dai-eastgate seems good to me! thank you for the quick adjustments. :) Can I label this as "in review"?

@fredericalpers yes, please help us to review. Thanks!
