### ISSUE TITLE
Missing field types

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#634]
Regarding [Issue 557](https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/557#issuecomment-1680219679).

> "Some fields are not displayed in the correct format "default value" feature for that field type. The reason is that the "field type" API result responses of these fields are not covered in the source code. These are the fields whose type is not covered in the code. Please check the file listed by name and type as follows.."

# Current state
The following field keys & types are missing as mentioed in the issue above:
- bisdatum ➤ urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:date
- balkon ➤ urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:tinyint
- benutzer ➤ urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:User
- Kundenlogo ➤ blob
- placeholderEnergy ➤ urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:BlackHint

# Desired state
### The following field keys & types should be added to the code:
- bisdatum ➤ urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:date
- balkon ➤ urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:tinyint
- benutzer ➤ urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:User (the frontend has to be a single select not a input field)

### The field keys & types _do not have_ to be added:
- Kundenlogo since it is not possible to transfer/send images to onOffice enterprise with the API.
- placeholderEnergy --> urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:BlackHint

**Comment by yeneastgate** [comment]
@fredericalpers 
1. For "urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:date" type fields: 
- We must submit "value for these fields" in "DateTime format" for example: "yy/mm/dd", "yy-mm-dd" or "yy.mm.dd" to create the correct data in Enterprise.
- In the master branch, these fields display in both the front-end and back-end as image below:
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/4439328e-aa37-4ee8-b4f6-6aa97708727f)
=> Would you like to keep this format or use a "date picker" format as shown in the image below?
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/2b114e27-fa34-4717-9a5e-beda5aa8a576)


2. For "urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:tinyint" type fields:
- We must submit "value for these fields" in "boolean format" for example: "0" corresponds to "No" or "1" corresponds to "Yes"

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/56cef991-b845-4deb-9311-1413e2d08024

- In the master branch, these fields display in the front-end and back-end as image below
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/cf83cc15-b976-46ca-87c0-7bd75ad56fdc)

=> Would you like to display them in a "boolean" format as shown in the image?
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/e487a888-d72d-4991-8f1f-6d0da4236910)

**Comment by fredericalpers** [comment]
@yeneastgate I will give you feedback on this tomorrow, thank you :)

**Comment by fredericalpers** [comment]
@yeneastgate As for no.1 please implement the suggested date picker. Make sure it has a good usability on mobile devices and it works in all browsers. E.g. Chrome, Firefox, Safari etc.

As for no.2 is it possible to use radio buttons instead of a select? This way we can show both possible values and its easier to change for customers.

**Comment by yeneastgate** [comment]
@fredericalpers I will try implementing it and will update the results for you ASAP.

**Comment by yeneastgate** [comment]
> As for no.1 please implement the suggested date picker. Make sure it has a good usability on mobile devices and it works in all browsers. E.g. Chrome, Firefox, Safari etc.

The "date picker" feature has been already implemented in the Estate List. I tested and it works fine.
Mobile devices:
iPhone 13 (1170 x 2532)
iPhone 7 (750 x 1334)
iPhone 6 (750 x 1334)
Ipad Gen 7 (2160 x 1620)
Realme 11 Pro (1080 x 2412)
 
Browsers:
Chrome: version 117, 107
Edge: version 117, 107
Opera: version 102, 98
Safari: 16.5.1
Do you want me to test it on any other specific browsers or mobile versions?

**Comment by yeneastgate** [comment]
@fredericalpers 
1. If there's no need for further testing, I will implement the 'date picker' feature similar to the one in the Estate List

2.**This is the list of fields** that will be implemented.
![list-fields](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/ca466c4d-ca65-4686-bcfc-5a38f2dd3d5d)
=> It will take 6 days to implement and test it. Thanks!

**Comment by fredericalpers** [comment]
@yeneastgate please go ahead and implement the date picker and the missing field list, thank you :)

**Comment by yeneastgate** [comment]
> @yeneastgate please go ahead and implement the date picker and the missing field list, thank you :)

OK. I will implement it.

**Comment by yeneastgate** [comment]
@fredericalpers I checked and found that:
To change from "input text" to "date picker", we need to edit the fields.php file, which may affect backward compatibility. 
Please give me your opinion on this matter.

**Comment by fredericalpers** [comment]
@yeneastgate please go ahead :)

**Comment by yeneastgate** [comment]
@fredericalpers 
Currently, in the form, I see fields with the type "Date" or "DateTime" being displayed as text
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/e98f0422-98ca-400c-810e-074d7159cae1)
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/a9d207ef-6158-4be8-8287-baec6dfa0d32)

=> Please confirm for me whether we need to change those types to "Date picker" or not.
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/6174cbdf-4349-4630-b4c4-da9be325ba0b)

**Comment by yeneastgate** [comment]
@fredericalpers  I have added types for the missing fields:
urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:date ("input text" => "date picker")
urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:tinyint ("input text" => "radio button")
urn:onoffice-de-ns:smart:2.5:dbAccess:dataType:User ("input text" => "single select"

Please watch my video demo and let me know your opinion. Thanks!
https://files.fm/u/tupe8yrwmx
