### ISSUE TITLE
Geo range search mandatory fields

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#641]
# Current state
If you use the geo range search, the fields "Country", "Radius" and "City" or "Postcode" are mandatory fields. The geo range search does not work without the mandatory fields. Customers forget to add the mandatory fields or intentionally deselect them despite being told not to do so.

# Desired state
The mandatory fields "Country" and "Radius" should always be checked and should not be deselectable. See screenshots below.

At the same time the info text below must be changed to: "At least city or postcode required". We would also like to implement a error message (like WordPress Error Messages) if one of the additional required fields is missing (city or postcode) when a customer is trying to save.

**Geo range search old:**
![OLD-geo-range-search](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/8511d592-16e7-400e-98ab-04860cceb167)

**Geo range search new:**
![NEW-geo-range-search](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/68a1e00f-c701-4d38-ac43-b0d4c5fe0378)

**Comment by yeneastgate** [comment]
@fredericalpers 
I have a solution to solve this issue.
Please confirm for me the error message when "one of the additional required fields is missing".
=> I have 2 options as follows: 
option 1:
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/1e401503-40eb-4937-a8e1-45b2856edc8a)

option 2:
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/928f87e7-4500-418e-bc8d-b73563c97088)

Which option do you want me to implement the error message?
It takes me 3 days to fix and test it. Thanks!

**Comment by fredericalpers** [comment]
@yeneastgate please implement option 1 :)

**Comment by yeneastgate** [comment]
> @yeneastgate please implement option 1 :)

I got it. Thanks

**Comment by dai-eastgate** [comment]
@fredericalpers 
I have fixed it exactly as "Desired state". Please watch my video demo and let me know your opinion about this. Thanks!
https://files.fm/u/nbk3vmvw82
Note:
For old users, the old config will still remain.
ex:  If the user had previously selected the street field, that configuration will still be reserved.

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/56aa4f75-29f5-433a-9b0f-c18b343859a3

**Comment by fredericalpers** [comment]
@dai-eastgate looks good to me, thannk you :)

**Comment by andernath** [comment]
@dai-eastgate 
Thanks for your commit I reviewed the code.

Your changes for required land and radius field looks good. 👍

But after some discussion we think the fields for postcode and city shouldn't be checkboxes, because the logic that at least one of them has to be selected fits more to readio button controls. 
We will create a new issue to change postcode and city to readio buttons for another release.

Could you revert all changes that implement postcode and city fields are required fields?
I think only admin.js and `wp_localize_script('admin-js', 'onOffice_loc_settings', ['page' => get_current_screen()->id]);` in AdminPageEstateListSettings.php has to be reverted.

**Comment by yeneastgate** [comment]
@andernath  I fixed it. Please watch my video demo. Thanks!

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/f8094a75-ecf7-437d-85e3-bd00a790888c
