### ISSUE TITLE
Custom label for "Land" and "land" field

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#644]
# Current state

While further investigating the current Issue
- https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/540

we realized that the custom labels do not work as intended. The custom label seem to overwrite each other. Possibly because the field names are not case-sensitive? In the frontend however the opposite value will be displayed. Please see the screenshot attached.

![custom-label-land](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/1d73ac58-0492-4192-a0b4-e5e3c196f1f5)

# Desired state
The custom labels for both fields should work correctly and not overwrite each other.

**Comment by yeneastgate** [comment]
@fredericalpers I will implement it. Thanks!

**Comment by yeneastgate** [comment]
@fredericalpers I fixed this bug. Please watch my video demo and let me know your opinions. Thanks!

https://files.fm/f/qpvapqtgef

**Comment by fredericalpers** [comment]
@yeneastgate seems to be working fine now, thank you :)
