### ISSUE TITLE
Implement City-Select into WP-Plugin

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#655]
# INITIATIVE 
Improve the usability of the onOffice for WP-Websites Plugin for a better user experience.

### EPIC ###
Implement a City-Select.

### USER STORY ###
As a real estate agent utilizing the onOffice for WP-Websites Plugin, I recognize the importance of providing a seamless and user-friendly property search experience for my customers. Currently, the city field is a simple search input, lacking the ability to display available cities where I have listed properties. 

To enhance the search functionality and optimize the user experience, I propose the implementation of a feature that transforms the city field into a select dropdown. This dropdown should dynamically populate with only the cities where I have listed properties, ensuring that customers can easily select from the available options.

- City field enhancement: Introduce a configuration option in the onOffice for WP-Websites Plugin that allows me to transform the city field in the property search into a select dropdown.
- Filter available cities: The dropdown should only display cities where I currently have properties listed. This ensures that customers can only select from the citites relevant to the available properties on my website. Show "Hide empty values from onOffice enterprise", but its disabled and therefore cannot be deselected by customers. See screenshot attached.
- Responsive design: The feature should be responsive, providing a consistent and optimal experience across various devices and screen sizes.
- Compatibility: The feature should be compatible with other search parameters and not interfere with the overall functionality of the property search.

By implementing this feature, the onOffice for WP-Websites Plugin can significantly enhance the property search experience for customers. This improvement ensures that customers have a straightforward and efficient way to select cities based on the available properties listed on my real estate website, contributing to a more user-centric and engaging property search process.

### TASKS 
- Add a new configuration option in the property list settings related to the city field.
Checkbox: "Display as selection list instead of text input." See screenshot attached. 
- Implement logic to transform the city input field into a select dropdown based on selected configuration.
- Develop logic to dynamically populate the dropdown with cities where the real estate agent has listed properties. Ensure that this population logic is efficient and does not impact the performance of the property search function.
- Implement user interaction functionalities for the dropdown, allowing users to click and select their city, while also being able to filter the city names with typing the respective city names. https://select2.org/getting-started/basic-usage
- Ensure that the dropdown feature is responsive and provides consistent user experience across various devices and screen sizes.
- Verify that the new feature is compatible with other search parameters and does not cause conflicts with the overall functionality of the property search.
- Conduct thorough testing of the new feature, including positive and negative test cases to ensure it works as expected.
- Address and resolve any bugs or issues identified during testing.

![ort2](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/aa8c0d42-603e-4662-9ecd-bd9624c20309)

**Comment by dai-eastgate** [comment]
@fredericalpers 
I found a solution to resolve this issue.
However, during implementation, I see a point below:

> ``Filter available cities: The dropdown should only display cities where I currently have properties listed. This ensures that customers can only select from the citites relevant to the available properties on my website.`` 

=> To resolve the above requirement, I will call an API to retrieve all the estates of the onOffice enterprise.
However, according to the API document (https://apidoc.onoffice.de/actions/datensatz-lesen/objekte/), each time call API, the response "listlimit" is 500 records
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/1dce893f-22ef-4344-9b04-79c50b22f43d)

So, if your clients have more than 500 estates, this solution is not possible. 
Please let me know your opinion on the above issue. Thanks!

**Comment by fredericalpers** [comment]
@dai-eastgate yes unfortunately there is the estate limit, but most of our customers do not have 500 published properties. Please go ahead and try to implement your solution. Thank you :)

**Comment by dai-eastgate** [comment]
> @dai-eastgate yes unfortunately there is the estate limit, but most of our customers do not have 500 published properties. Please go ahead and try to implement your solution. Thank you :)

Thanks. I need 5 days to implement and test it.

**Comment by dai-eastgate** [comment]
@fredericalpers 
I would like to confirm with you a point:
To implement this feature, we must edit "fields.php" in the "template.dist" directory.
=> Old users need to update "template.dist" for this feature to work properly.
Please let me know your opinion about this. Thanks!

**Comment by fredericalpers** [comment]
@dai-eastgate I will get back to you on this asap, let me confirm with my colleagues again :)

**Comment by dai-eastgate** [comment]
> @dai-eastgate I will get back to you on this asap, let me confirm with my colleagues again :)

@fredericalpers
Do you have any updates for this issue?

**Comment by dai-eastgate** [comment]
@fredericalpers 
Please watch my video demo and let me know your opinion about this. Thanks!
https://files.fm/f/f5gngnwef8

Note: As I mentioned before "Old users need to update "template.dist" for this feature to work properly"

**Comment by fredericalpers** [comment]
@dai-eastgate thank you :) after finallybeing able to discuss this with my colleagues today I have the following feedback:

We are aware that our customers have to update their fields.php after the update. Therefore we want to implement a notice under the checkbox explaining it and link to our documentation for detailed explanation. I will send you the text and link next week, after I returned from my vacation.

Also we want to confirm that even when a customer does not update the fields.php the functionality of the city-field must still be given as before. (text input)

**Comment by dai-eastgate** [comment]
> @dai-eastgate thank you :) after finallybeing able to discuss this with my colleagues today I have the following feedback:
> 
> We are aware that our customers have to update their fields.php after the update. Therefore we want to implement a notice under the checkbox explaining it and link to our documentation for detailed explanation. I will send you the text and link next week, after I returned from my vacation.
> 
> Also we want to confirm that even when a customer does not update the fields.php the functionality of the city-field must still be given as before. (text input)

@fredericalpers I got it. Thanks!

**Comment by dai-eastgate** [comment]
> Also we want to confirm that even when a customer does not update the fields.php the functionality of the city-field must still be given as before. (text input)

@fredericalpers 
Yes, this will be ensured. Please take a look at my attached video.

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/8d38871f-721d-4b6d-9eee-31a6b4ac0740


> Therefore we want to implement a notice under the checkbox explaining it and link to our documentation for detailed explanation.

By the way, I have implemented a notice below this checkbox. Please see the attached photo. ^^
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/7676d8df-4464-496b-b0fd-7df13b28fd08)

**Comment by fredericalpers** [comment]
@dai-eastgate looks good to me, thank you :)

**Comment by andernath** [comment]
@dai-eastgate could you take a look at the unit tests? They are failing after merging this branch in master.

**Comment by dai-eastgate** [comment]
@andernath I will check
