### ISSUE TITLE
Clear cache with admin bar quick action on multisites

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#661]
# Current State
With multisites, the cache cannot be cleared with the quick action "Clear cache" in the admin bar. It'll lead to a URL like: https://multisite-domain/wp-admin/onoffice-clear-cache which causes an error as seen below.

```
Not Found
The requested URL was not found on this server.
```

# Desired State
The quick action "Clear cache" should also work for multisites.

**Comment by dai-eastgate** [comment]
@fredericalpers For this issue, I am working on it and will get back to you soon.

**Comment by yeneastgate** [comment]
@fredericalpers I fixed this bug. Please watch my video demo and let me know your opinion. Thanks!
https://files.fm/u/5r9q3mz5tz

**Comment by fredericalpers** [comment]
@yeneastgate looks good to me, is there anyway you can also test this on an actual WordPress Multisite or am I missing something?

**Comment by yeneastgate** [comment]
> @fredericalpers I fixed this bug. Please watch my video test on WordPress Multisite and let me know your opinion. Thanks!
> **This feature still works fine on multisites.**
> https://files.fm/u/5r9q3mz5tz#/view/893bvprrdy
there anyway I can also test this on an actual WordPress Multisite

**Comment by fredericalpers** [comment]
@yeneastgate I'm blind, sorry :D thank you for the quick fix.
