### ISSUE TITLE
Form can not be sent with unfilled required fields and enabled recaptcha 

### ISSUE THREAD

**Issue by andernath** [onOffice-Web-Org/oo-wp-plugin#669]
While testing #648 I have found 2 bugs in forms that have required fields and use reCAPTCHA.

### Major bug 1: 
Form can not be sent. See **Picture 03**.
To reproduce the bug:
- open a form with required field and enabled recapcha
- just send form (WITHOUT touching any input fields)

Now the sending button turn disbaled because you did not fill all required fields, but no hint will be shown. There is no way to enable the sending button again.

### Minor bug 2: 
Styling of required field hint is wrong. **Picture 02**.
To reproduce the bug:
- open a form with required field and enabled recapcha
- click inside an input field without filling it
- send form

Hint will be displayed but not with the same text and style like **Picture 01**.

_______________________________________________________________________________________________
**Picture 01** (Hint if no recapcha is enabled and user did not fill required field)
![01_required_hint](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/22166320/0fee0143-3525-4f7b-abe2-69089920c16b)
**Picture 02**
![02_required_hint_with_recapcha](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/22166320/72238d04-256e-43d5-a996-4aa67d15d927)
**Picture 03**
![03_required_hint_recapcha_not_loaded](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/22166320/c2a00846-1879-42a2-a56a-c32d0e88474e)

**Comment by dai-eastgate** [comment]
@andernath I will check and let you know asap. Thanks!

**Comment by dai-eastgate** [comment]
@fredericalpers @andernath 
> Major bug 1:

I have fixed this bug. Please watch my video demo

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/1add8f38-ba8a-4f8e-b442-1a15b0dc8d68



> Minor bug 2:

I have fixed this bug. Please watch my video demo

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/6a769b3a-87b7-450e-b86a-63c4f13bdff9

Note: I have implemented "reCAPTCHA correctly for each form" to follow in this linked document (https://developers.google.com/recaptcha/docs/display#explicit_render)

**Comment by andernath** [comment]
Good work @dai-eastgate 
I will review and test ist later.
