### ISSUE TITLE
API user rights check

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#676]
# Initiative
Improve the usability of the onOffice for WP-Websites Plugin for a better user experience.

### Epic
Implement a API user rights check.

### User story
As a real estate agent using the onOffice for WP-Websites Plugin, I need a healthcheck feature that not only validates the correctness of my API token and secret but also ensures that my API user rights are configured accurately. This additional check will help prevent issues such as missing property data or contacts not displayin properly on my website due to incorrect user rights settings.

As part of my real estate business, I rely on the seamless integration between my onOffice enterprise account and my WordPress website through the onOffice for WP-Websites Plugin. While entering the API token and secret is crucial, its equally vital that the API user rights are configured correctly. Misconfigured rights can lead to data inconsistencies and hinder the smooth operation of my website.

I request the implementation of an API user right check in the plugin. This check should alert me when the API user rights are not set correctly, preventing potential disruptions in data transmission.

- The feature should assess whether the API user rights (as seen in the screenshot) are set correctly. It should check the rights associated with my API credentials for the necessary privileges required to display properties etc.
- If any discrepancies or incorrect user rights are detected during the health check, I want to receive a clear and comprehensive notification. This can be in form of an alert within the plugin, ensuring I'm promptly informed about any issues.

https://apidoc.onoffice.de/actions/datensatz-lesen/read-user-rights/

By implementing this API user right check, the onOffice for WP-Websites Plugin can offer real esatet agents a proactive way to  ensure the correct configuration of API user rights, minimizing disruptions in data transmissions and contributing to a more reliable and user-friendly experience.

### Tasks
• Develop logic for checking the correctness of API user rights.
• Integrate the necessary modifications to the backend settings interface to accomodate the new API user right check functionality.
• Implement real-time feedback mechanism to provide immediate alerts when API user rights are inccorectly configured.
• Develop a notification mechanism to alert users immediately if the API user rights are not configured correctly.

**Process Design**
![check-api-user-rights (1)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/a0d83fef-da07-4d75-8326-0cf87618ed7b)

**Button Test API user rights**
![button-test-api-user-rights (1)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/bf7f6e74-d056-4573-ac61-5a364ea90195)

**API user rights check feedback**
![button-test-api-user-rights_results (1)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/dbfe3bfd-cd00-4350-bc8b-79a609e4834c)

**Comment by dai-eastgate** [comment]
@fredericalpers For this issue, I am working on it and will get back to you soon.

**Comment by fredericalpers** [comment]
@yeneastgate I will check and let you asap :)

**Comment by fredericalpers** [comment]
Unfortunately this feature is blocked for now...

**Comment by fredericalpers** [comment]
unfortunately, the feature cannot be implemented at the moment. it may be reopened in the future.

**Comment by fredericalpers** [comment]
unfortunately, the feature cannot be implemented at the moment. it may be reopened in the future.
