### ISSUE TITLE
Price is emptied when property search is executed

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#679]
# Initiative
Improve the usability of the onOffice for WP-Websites Plugin for a better user experience.

### Epic
Improve the property search.

### Userstory
As a real estate agent leveraging the onOffice for WP-Websites Plugin, I find it inconvenient that the filtered price is reset upon submitting the property search form. To enhance the user experience and alleviate repetitive data entry, I request the implementation of a feature that preserves the filtered price value until explicitly modified or upon leaving the page. This improvement aims to optimize the property search process, allowing users to seamlessly refine their search without the need to repeatedly input the price criteria.

The current behavior of the property search feature results in the cleared state of the filtered price after each form submission. This can be frustrating for users who wish to make slight adjustments to their search cirteria without re-entering the entire set of filters.

- [x] Assess the current codebase related to property search functionality
- [x] Identify the logic responsible for resetting the price filter upon form submission
- [x] Modify the code to ensure that the filtered price value persists after form submission

By adressing these tasks, the onOffice for WP-Websites Plugin can offer a more user-friendly property search experience, especially concering the persistence of the filtered price value.

**Comment by yeneastgate** [comment]
@fredericalpers I need time to check it and will let you know soon.

**Comment by yeneastgate** [comment]
@fredericalpers I found a solution and need a day to implement and test it. Thanks

**Comment by yeneastgate** [comment]
@fredericalper I fixed "price is emptied when property search is executed". Please take a look at my video demo.

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/3b8adccf-0e7a-424b-97b2-136e9457479e

Note: During testing, I found that the filtered "date" field (ex: created on) is reset upon submitting the property search form like the "price" field. Do you want me to fix the "date" type in this issue too?

**Comment by fredericalpers** [comment]
@yeneastgate please go ahead and fix this for the date type too, thank you :)

**Comment by yeneastgate** [comment]
> @yeneastgate please go ahead and fix this for the date type too, thank you :)

I got it. Thanks!

**Comment by yeneastgate** [comment]
> @yeneastgate please go ahead and fix this for the date type too, thank you :)

I fixed the "date" type. Here is my video demo

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/ba00642b-85d0-407c-8865-0146a3ab022c
