### ISSUE TITLE
Multiple contact types in form-specific options

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#751]
# Initiative 
Improve the usability of the onOffice for WP-Websites Plugin

### Epic
Change the type of contact address field from single to multiselect

### User story
As a real estate agent utilizing the onOffice plugin, I find the current single-select option for defining the contact types in form-specific settings limiting. In onOffice enterprise, this functionality is designed as a multi-select field, allowing for the selection of multiple contact types. To align the plugin's capabilities with onOffice enterprise and enhance flexibility, I propose transforming the contact type selection into a multi-select field integrated with Select2.

The existing form-specific options in the onOffice plugin allow for the definition of the contact type associated with the created address. However, the current implementation restricts users to a single contact type. Recognizing the need for more versatility, I propose the change to a multi-select field.

### Tasks

- [x] Identify and modfiy the code related to form-specific options to enable multi-select functionality
- [x] Integrate the Select2 library and ensure its proper functionality

By implementing these changes, real estate agents using the onOffice plugin will have a more robust and flexible system for defining contact types in their forms.

**Comment by dai-eastgate** [comment]
@fredericalpers I have found a solution for this task, and I need 4 days to implement it. Thanks!

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented it and this is video
- For Interest Form: https://files.fm/u/p3tz3d7az8
- For Contact Form: https://files.fm/u/ucznjb4wv3
- For Owner Form: https://files.fm/u/3mhj8e9t4w
Please check and let me know your opinion. Thank!

**Comment by fredericalpers** [comment]
> @fredericalpers I have implemented it and this is video
> 
> * For Interest Form: https://files.fm/u/p3tz3d7az8
> * For Contact Form: https://files.fm/u/ucznjb4wv3
> * For Owner Form: https://files.fm/u/3mhj8e9t4w
>   Please check and let me know your opinion. Thank!

looks good to me! and seems to be working as intended,thank you :)
