### ISSUE TITLE
Change info text for SEO title and description settings

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#776]
We would like to adjust the info text regarding the SEO settings for titles and descriptions on the plugins settings page.

### English:

With the help of an SEO plugin, it is possible to use individual fields to insert data directly from onOffice enterprise into the title and metadata of your website. 

These custom fields allow you to insert specific information, such as the property title and property number from onOffice enterprise. The corresponding field names can be found in the field list on the detail page. Please note that only fields that are active for the detail page, for example, can be output.

An example of integration with the Yoast SEO plugin would be:
`%%cf_onoffice_objekttitel%%` or
`%%cf_onoffice_objektnr_extern%%` or
`%%cf_onoffice_objektbeschreibung%%`

For information on how to use custom fields in your SEO plugin, please refer to its documentation.

### Old text:

![seo_einstellungen (2)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/da79809f-33ae-421c-8d8c-bdfc17386a10)

- [x] Change text

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented it and this is demo video

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/73a7a0de-a5ab-4a9f-b52e-77c5403bcbde

Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
> @fredericalpers I have implemented it and this is demo video
> 
>  bandicam_2024-03-21_13-10-00-935.mp4 
> Please check and let me know your opinion. Thanks!

Can you also please edit "Custom fields" into "Further information on custom fields"?

I just also realized that it would be helpful for our customers if the cursor would change to, so they will actually realize they are able to open this for more information.

**Comment by dai-eastgate** [comment]
@fredericalpers Ok, I got it

**Comment by dai-eastgate** [comment]
@fredericalpers I have updated it. This is demo video: https://files.fm/u/d24yauqbps#/view/p4ngyna3bh
Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
> @fredericalpers I have updated it. This is demo video: https://files.fm/u/d24yauqbps#/view/p4ngyna3bh Please check and let me know your opinion. Thanks!

please don't forget to add the `cursor: pointer;` for the details, so customers get a visual feedback, that they can actually open this. Thank you :)

**Comment by dai-eastgate** [comment]
@fredericalpers  I got it

**Comment by dai-eastgate** [comment]
@fredericalpers I have updated it. This is demo video 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/514e88d3-f011-4b3a-81a4-9953bf1756ac

**Comment by fredericalpers** [comment]
> @fredericalpers I have updated it. This is demo video
> 
>  UpdateCursorPointer.mp4

I will have to trust you on this one :D I can not see the cursor in the recording. Thank you :)

**Comment by dai-eastgate** [comment]
@fredericalpers It was my mistake, my recording application crashed. Please recheck the video below:

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/b708a5b7-e857-41bc-8b7d-c5e650a1182c
