### ISSUE TITLE
Integration of Price on Request with calculatedPrice field

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#789]
# Integration of Price on Request with calculatedPrice field

### Introduction
calculatedPrice checks for the marketing type rent or purchase and then fills in the values of the field purchase price or rental price. This is particularly helpful for the output in the front end of the website, as you only have to add one field (calculatedPrice) and no longer have to add any dependencies for only displaying rental prices or only displaying purchase prices.

### User Story
As a user of the onOffice for WP-Websites plugin, I sometimes rely on the Price on Request feature to not display prices on my website. I've encountered issues where the Price on Request feature functionality does not properly interact with the "calculatedPrice'' field. These inconsistencies in functionality detract from the overall user experience and may lead to confusion among users.

By ensuring compatibility with the Price on Request feature, users will benefit from consistent and accurate pricing information, enhancing their overall experience when working with calculated Prices.

### Requirements / Tasks

- [x] Conduct an analysis of the current implementation of the "calculatedPrice" field and its interaction with the Price on Request feature.
- [x] Identify the missing configurations or integrations that prevent the Price on Request feature from working with the "calculatedPrice" field.
- [x] Develop a solution that the Price on Request feature is properly supported.
- [x] Conduct comprehensive testing to ensure that the changes resolve the issue and do not introduce any new issues.

**Comment by fredericalpers** [comment]
>And currently, the "Price on Request" feature is not affecting the "calculatedPrice" field.
=> Is this statement about "calculatedPrice" correct or not?

correct, price on request is not affecting the "calculatedPrice" field, but it should be added to the field list.

>During implementation, I see you are setting the label as "component: unit list". However, I found that the unit list does not have the feature to "show price on request".
=> Is this a confusion between similar estates and unit list?

this is indeed wrong. thank you! :)

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented it. This is video demo https://files.fm/u/3af2chf47d#/view/hb9v4n4ykw
Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
> @fredericalpers I have implemented it. This is video demo https://files.fm/u/3af2chf47d#/view/hb9v4n4ykw Please check and let me know your opinion. Thanks! Note: Unit test will work after merge PR #792

@dai-eastgate looks good to me! thank you :) we will review this soon

**Comment by fredericalpers** [comment]
@dai-eastgate Thank you for the new feature with the "calculatedPrice" field. Unfortunately, it currently only works correctly in the property listing. On the property detail page and for similar properties, the price is still being displayed, even though "Price on Request" is activated both in onOffice enterprise and in the plugin.

Could you please check if the "calculatedPrice" field is applied correctly on the detail page and for similar properties? The price should not be displayed there, just like in the property listing, when "Price on Request" is active.

Thanks for your efforts and adjustments!

**Comment by dai-eastgate** [comment]
@fredericalpers I have checked and fixed it. Please verify it again. Thank you!
