### ISSUE TITLE
Revision of the address list template for enhanced representation of addresses, franchises, offices and agents

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#797]
# Revision of the address list template for enhanced representation of addresses, franchises, offices and agents

### Introduction
The address list feature in the onOffice plugin, while often overlooked, serves a crucial purpose when utilized – displaying franchise locations and their associated agents. In industries like real estate, where connectivity and organization are paramount, address lists can become an invaluable tool for showcasing available properties and facilitating client-agent interactions. Whether presenting franchise branches or office locations, these lists offer a centralized platform for efficiently connecting clients with their agents. Despite the underutilization, address lists remain indispensable for streamline communication and fostering connectivity within the real estate landscape.

### User Story
As a real estate company with multiple franchise locations, it is crucial to provide an effective means of searching for franchise locations, offices and their associated agents on our website. Currently, the address list template in the plugin is inadequate, as it displays images only as URLs and presents data without proper formatting and HTML semantics. To ensure an appealing and user-friendly representation, I propose revising the address list template.

By revising the address list template, real estate companies can present a user-friendly and visually appealing means of searching for franchise locations, offices and agents on their website, leading to enhanced user interaction and customer engagement.

### Requirements / Tasks

- [x] Analyze the current address list template and identify weaknesses regarding image display, data formatting and HTML semantics.
- [x] Develop an updated version of the address list template that includes the complete "img src" set for images and presents data in a structured and semantically correct HTML format. See property lists.
- [x] Conduct comprehensive testing to ensure that the revised address list template functions correctly and provides an improved user experience.

**Comment by dai-eastgate** [comment]
> enhanced representation of addresses, franchises, offices and agents

@fredericalpers I see you're mentioning "addresses, franchises, offices and agents". According to my research in onOffice enterprise:
- Fields for "addresses": Solution, First name, Name, Company, Email, Phone number, Fax number
- Fields for "franchises": wB First name, wB Name, wB Street, wB Postcode, wB City, wB Citizenship, wB Place of birth, wB Date of birth
- Fields for "offices": Currently I can't find relevant information.Please help me provide fields related to the "office"
- Fields for "agents": Contact type
=> **Is the information I gave correct? If not, please point out to me the incorrect information?**

Currently, I see the default field includes: Salutation, First name, Name, Company, Email, Phone number, Fax number
=> **Do you want to add other fields to the default fields to "enhanced representation of addresses, franchises, offices and agents"?** If so, please list them for me.


> * Develop an updated version of the address list template that includes the complete "img src" set for images and presents data in a structured and semantically correct HTML format. See property lists.

Would you like to implement a "picture tag" feature similar to the issue https://github.com/onOffice-Web-Org/oo-wp-plugin/issues/675?

**Comment by fredericalpers** [comment]
@dai-eastgate theres no need to change the default for the display of the list. Please also implement the "picture tag" feature, thank you :)

**Comment by dai-eastgate** [comment]
> Would you like to implement a "picture tag" feature similar to the issue #675?

@fredericalpers In the estate list, we just need to add the width and height to the image URL to crop the image. Please see the function below:
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/07ab79f4-fabb-469f-97e2-506a159abb88)
But in the addresses list, "imageUrl" in the Parameter "data" of API read addresses does not support image cropping.
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/f1301d38-8a0c-4f27-8855-4718792b780e)
=> We cannot implement the "picture tag" feature in the addresses list
Please check with the IT department and let me know how to use crop images in the address list

**Comment by fredericalpers** [comment]
@dai-eastgate you are right, when I was writing the user story we were still waiting for feedback from our IT department. The pass photo is automatically cropped to 300x200 when uploaded to onOffice enterprise, therefore it is not possible to crop/edit it. Please ignore the picture tag feature for now. Just make sure, the imageURL is actually displayed as an image instead of just the URL.

We will be implementing a new feature in the next cycle that builds on your current work on this issue. More information on this in the next cycle :) thank you

**Comment by dai-eastgate** [comment]
@fredericalpers I got it

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented and here is video demo: https://files.fm/u/axwdatpxhk#/view/74xucjnh9m
**Note:** Currently, I have set the alt tag as alt="address-img". Please check the video and tell me what the value of the alt tag should be?

**Comment by fredericalpers** [comment]
> @fredericalpers I have implemented and here is video demo: https://files.fm/u/axwdatpxhk#/view/74xucjnh9m **Note:** Currently, I have set the alt tag as alt="address-img". Please check the video and tell me what the value of the alt tag should be?

looks good to me! :) thank you for the implementation.

The alt-tag should always be the name, companies name or the offices name, depending on if it is an actual person, company or a office of a company.

**Comment by dai-eastgate** [comment]
> The alt-tag should always be the name, companies name or the offices name, depending on if it is an actual person, company or a office of a company.

@fredericalpers I don't understand what you mean. I see you are mentioning 3 types of names to be set value for the image alt attribute: "name", "companies name", "the offices name".
**When does an image of an address have alt tag as "name", "company name", "the offices name"?**
Note: According to my research
- "name": is the "Name" field on the onOffice enterprise
- "companies name": is the "Zusatz1" field on the onOffice enterprise
- "the offices name": I couldn't find this field. **Please tell me the key of office name**

**Comment by fredericalpers** [comment]
The following are the possible fields that should be used respectively.

Private Customer = fieldnames: Vorname, Name
Business Customer = fieldnames: Vorname, Name
Company = fieldname: Zusatz1
Office = fieldname: branch 
Joint heirs = fieldname: communityOfHeirs
Owner's association = fieldname:communityOfOwners
Umbrella organization = fieldname: umbrellaOrganization
Mr & Mrs = fieldname: Name
Association = fieldname: association
Institution = fieldname: institution

**Comment by dai-eastgate** [comment]
@fredericalpers I added content to the image alt this is video evidence: https://files.fm/f/6hp9d25dwg

> The following are the possible fields that should be used respectively.
> 
> Private Customer = fieldnames: Vorname, Name Business Customer = fieldnames: Vorname, Name Company = fieldname: Zusatz1 Office = fieldname: branch Joint heirs = fieldname: communityOfHeirs Owner's association = fieldname:communityOfOwners Umbrella organization = fieldname: umbrellaOrganization Mr & Mrs = fieldname: Name Association = fieldname: association Institution = fieldname: institution

In the contact category list you gave me, I see that a contact category is missing, department.
=> Currently, for the contact category "department", the corresponding field I am setting is "department".
Please check and let me know your opinion

**Comment by fredericalpers** [comment]
@dai-eastgate please go ahead and also implement "department", thank you :)

**Comment by dai-eastgate** [comment]
> @dai-eastgate please go ahead and also implement "department", thank you :)

@fredericalpers I have implemented it in this PR, please check it again. Thanks!

**Comment by fredericalpers** [comment]
In anderem Branch zusammengeführt und bereits released.
