### ISSUE TITLE
Improvement of the address list functionality - Add Detail page (1)

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#805]
# Improvement of the address list functionality - Add Detail page (1)

### Introduction
The current functionality of the onOffice for WP Websites plugin offers limited options for displaying employees, offices or locations on a real estate agent's website. In order to meet the needs of real estate agents and to enable a comprehensive display of employees, offices and locations, an extension of the functionality in the plugin is required.

### User Story
As a real estate agent, I would first like to implement the functionality for individual detailed views of my employees, offices and locations in the onOffice for WP Websites plugin. In a first step, the tabmenu for the detailed view and the settings for the field list and the field list search will be integrated.

By extending the functionality for the employees, offices and locations display in the onOffice for WP-Websites plugin, real estate agents can effectively use their website to present their teams and locations in an appealing way and to better inform potential customers.

### Requirements / Tasks

- [x] Development of the new tab "Detailed view" in the backend of the onOffice for WP-Websites plugin under the menu item "Addresses".
- [x] Implementation of the field list + field list search for contact person data / address data, which makes it possible to add or remove relevant information.
- [x] Ensuring that the extended functionality is seamlessly integrated with the existing plugin to ensure good usability.

### Design / Screenshots

![addresslisten-tabs](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/7acfd630-8462-48b8-bdc4-79606b20b44b)

![fieldlist-1](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/583e6969-1bb5-4384-b47f-3095466768af)

**Comment by yeneastgate** [comment]
@fredericalpers For your list of issues related to "Improvement of the address list functionality", I understand that you want to create an address detail page.

I have listed the features of the estate detail page in the table below and note the features that can be implemented similarly in the address detail page. The "x" refers to the features that needn't be implemented in the address detail page. 

![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/f91fadf7-476d-4281-8462-654b48e0bf03)

Can you please confirm for me the above features? Also, will  the default_detail template for address be implemented for the interface as well?

**Comment by fredericalpers** [comment]
@yeneastgate I can confirm the above comparison. Besides the missing selection for property lists (#808).

I'm not sure what you mean by "implemented for the interface"? If you are talking about a frontend template? I'm currently designing the frontend layout for the next steps :)

**Comment by yeneastgate** [comment]
> @yeneastgate I can confirm the above comparison. Besides the missing selection for property lists (#808).
> 
> I'm not sure what you mean by "implemented for the interface"? If you are talking about a frontend template? I'm currently designing the frontend layout for the next steps :)

@fredericalpers I got it. Thank!

**Comment by yeneastgate** [comment]
@fredericalpers What are the default fields in the address details?  They are these fields you have mentioned in the photo above, aren't they?
Do you want to implement custom labels for address details?

**Comment by fredericalpers** [comment]
@yeneastgate the default fields are already implemented. I checked the task.

The custom label feature is actually a good idea. Please go ahead and implement them here as well, thank you :)

**Comment by yeneastgate** [comment]
@fredericalpers I got it

**Comment by fredericalpers** [comment]
> @yeneastgate the default fields are already implemented. I checked the task.
> 
> The custom label feature is actually a good idea. Please go ahead and implement them here as well, thank you :)

Sorry for the confusion, this is a wrong statement from me. The default fields should be the same as the addresslists. I've mistaken it for the addresslists itself.

**Comment by yeneastgate** [comment]
@fredericalpers I have implemented it. These are demo videos for each feature:
1. General feature:
https://files.fm/u/ecrf9nkkgc#/view/we6n8wvs92

2. Field list search:

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/82ffa196-34aa-405f-a6c5-e42a52a753a6

3. Custom label:

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/5faa7a0c-941a-44c6-9aeb-44b7b7497ed2

*Notice: the Address list and notification still work normally

Please check and let me know your opinion. After you've designed the frontend layout, I will transfer the data to the UI

**Comment by yeneastgate** [comment]
> If you are talking about a frontend template? I'm currently designing the frontend layout for the next steps :)

@fredericalpers Does this pull request only implement logic in the backend?
And the logic deployed in the FE part be created in another pull request that will implement the FE you mentioned above?

**Comment by fredericalpers** [comment]
> > If you are talking about a frontend template? I'm currently designing the frontend layout for the next steps :)
> 
> @fredericalpers Does this pull request only implement logic in the backend? And the logic deployed in the FE part be created in another pull request that will implement the FE you mentioned above?

this Pull Request only implements the logic in the backend, a new Pull Request will be made for the frontend :)

**Comment by fredericalpers** [comment]
In anderem Branch zusammengeführt und bereits released.
