### ISSUE TITLE
Improvement of the address list functionality - Add form selection (3)

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#807]
# Improvement of the address list functionality - Add form selection (3)

### Introduction
The current functionality of the onOffice for WP Websites plugin offers limited options for displaying employees, offices or locations on a real estate agent's website. In order to meet the needs of real estate agents and to enable a comprehensive display of employees, offices and locations, an extension of the functionality in the plugin is required.

### User Story
After the functionality for individual detailed views of employees, offices and locations in Issue #806 has been improved in the onOffice for WP-Websites plugin, an additional extension is now to be made. This extension includes the option of selecting forms previously created in the plugin and integrating them into the detailed view. 

This allows real estate agents to further optimize their website by using specific forms to represent their teams and locations. This functional enhancement helps to improve customer interaction and provide potential customers with even more targeted information.

### Requirements / Tasks

- [x] Integration of a functionality to select a created form of the onOffice plugin and its display in the detail view. (also see property detail view form selection)
- [x] Ensuring that the extended functionality is seamlessly integrated with the existing plugin to ensure smooth use.

### Design / Screenshots
![address-detail-forms](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/f110cecf-940d-4296-b6c4-9f87094e0cbc)

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented backend logic for this issue. Here is video evidence: 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/2a8afc34-9f55-4198-a5cd-cd40ddde4a38

Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
@dai-eastgate is it possible here, analogous to the logic of the form on the property detail page, to build the logic in such a way that the selected form is only sent to the address data record/broker on the detail page? regardless of which email address is stored in the form.

**Comment by dai-eastgate** [comment]
> @dai-eastgate is it possible here, analogous to the logic of the form on the property detail page, to build the logic in such a way that the selected form is only sent to the address data record/broker on the detail page? regardless of which email address is stored in the form.

@fredericalpers Yes, it is possible to build the logic in such a way that the selected form is only sent to the address data record/broker on the detail page, regardless of which email address is stored in the form. I think we can implement this. I will try to implement it.

**Comment by fredericalpers** [comment]
@dai-eastgate thank you :)

**Comment by fredericalpers** [comment]
In anderem Branch zusammengeführt und bereits released.
