### ISSUE TITLE
Improvement of the address list functionality - Add property list selection (4)

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#808]
# Improvement of the address list functionality - Add property list selection (4)

### Introduction
The current functionality of the onOffice for WP Websites plugin offers limited options for displaying employees, offices or locations on a real estate agent's website. In order to meet the needs of real estate agents and to enable a comprehensive display of employees, offices and locations, an extension of the functionality in the plugin is required.

### User Story
Following the integration in XXX of forms into the detailed view for employees, offices and locations in the onOffice for WP Websites plugin, the next step is to add a new functionality. This functionality makes it possible to select already created real estate lists in the plugin and integrate them into the detailed view.

This allows real estate agents to further optimize their website by using specific property lists of the linked agents, offices, locations. This enhancement helps to improve customer interaction and provide potential customers with even more targeted information.

### Requirements / Tasks

- [x] Implementation of a checkbox to load the properties connected to the respective real estate agent.
- [x] Add Reference propertie selection (also see property lists feature)
- [x] Add Filtering
- [x] Add properties per page (also see property lists feature)
- [x] Add "Show property status" checkbox
- [x] Add "Show Price on Request" checkbox
- [x] Add "Show Property Map" checkbox
- [x] Ensuring that the extended functionality is seamlessly integrated with the existing plugin to ensure smooth use.

### Design / Screenshots

**EDIT:**

The implementation has to be closer to "similar estates", see the screenshot below:

![properties](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/fec11bb0-6668-42ce-9174-0e366cbedafb)

**Comment by fredericalpers** [comment]
@dai-eastgate I hope you did not work on this a lot already.. I unfortunately have to make changes to this. I realized that this feature improvement is not ideal yet. Sorry in advance

**Comment by dai-eastgate** [comment]
@fredericalpers  Currently I have tried implementing this issue in the backend logic. It's okay, I will stop the implementation for now

**Comment by fredericalpers** [comment]
@dai-eastgate I updated everything, if you have any further questions please let me know :)

**Comment by dai-eastgate** [comment]
@fredericalpers  After investigating this issue, I need to confirm the following issue:
Does address detail URL have feature " "Show title in URL" same estate detail URL?  
See the picture of the  "Show title in URL" below: 
![image](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/2b259a8b-3209-4066-80bb-540be3ef10fe)

**Comment by fredericalpers** [comment]
@dai-eastgate if possible this would be a good addition :)

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented backend logic for this issue. Here is video evidence:
https://files.fm/f/hpdaa5h9ts

Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
@dai-eastgate we will review this as soon as possible, thank you :)

**Comment by fredericalpers** [comment]
@dai-eastgate  after a second round of feedback and careful consideration of all our customers wishes, we unfortunately have to change it back to the initial request. with a dropdown selection for a property list. additionally we need a second dropdown where it's possible to select another property list, so we can display 2 lists. one with active properties and one e.g. with reference properties. thank you :) 
 
sorry in advance for the inconvenience.

**Comment by andernath** [comment]
@dai-eastgate 
After you updated a second dropdown here:
Could you please also create one single branch for testing and reviewing where these branches: 47941 47943 47944  47945 are merged in?

Because I can not resolve all merging conflicts by myself and it is difficult to review all changes in 4 different branches.

**Comment by fredericalpers** [comment]
> @dai-eastgate After you updated a second dropdown here: Could you please also create one single branch for testing and reviewing where these branches: 47941 47943 47944 47945 are merged in?
> 
> Because I can not resolve all merging conflicts by myself and it is difficult to review all changes in 4 different branches.

Please merge the branches first and then rework/add my comments tasks.

**Comment by dai-eastgate** [comment]
@fredericalpers @andernath I got it

**Comment by dai-eastgate** [comment]
![image](https://github.com/user-attachments/assets/7bccb1e0-a960-479d-aeeb-799bbb6f184f)

@fredericalpers Do you want to remove all the options above and only keep 2 dropdowns to display estates, allowing the selection of "Active Property" and "Reference Property"?

**Comment by fredericalpers** [comment]
> ![image](https://private-user-images.githubusercontent.com/106214469/361365715-7bccb1e0-a960-479d-aeeb-799bbb6f184f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzM0NjUsIm5iZiI6MTcyNDY3MzE2NSwicGF0aCI6Ii8xMDYyMTQ0NjkvMzYxMzY1NzE1LTdiY2NiMWUwLWE5NjAtNDc5ZC1hZWViLTc5OWJiYjZmMTg0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxMTUyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGNmYjg2MDJmMTdhMWFkMTMzNzg3M2U4OThlZGQxODE1OWI2Y2ZjNjVmZGU2ZGIzM2I0MzBmZDAzMDdiNzdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CeQUYFZ10nNgo9p4jO2fa1_3HT7ZN60_JF6roPM_D4U)
> 
> @fredericalpers Do you want to remove all the options above and only keep 2 dropdowns to display estates, allowing the selection of "Active Property" and "Reference Property"?

@dai-eastgate yes. all the other settings have to be made in the property lists. Here we only want to leave the customer the choice to choose which lists will be displayed.

**Comment by andernath** [comment]
@dai-eastgate 
Is this the merge branch of all new features for Addresslist and addressdetail? https://github.com/onOffice-Web-Org/oo-wp-plugin/tree/52295-improvement-of-the-address-list-functionality

I need this code to add a template for address detail page.

**Comment by andernath** [comment]
> However, this branch currently only contains the backend interface code as per the task requirements. We have not yet added the logic for the front-end. Do you need us to add it?
 @dai-eastgate 
thanks.
I noticed and already added amissing controller to my local branch. If i need any help I will ask you. :)

**Comment by fredericalpers** [comment]
In anderem Branch zusammengeführt und bereits released.
