### ISSUE TITLE
Redirection error if the url contains parameters

### ISSUE THREAD

**Issue by ingoKrOffice** [onOffice-Web-Org/oo-wp-plugin#811]
In v4.16 [Detail Page > Needed Filter Hook or Option to stopping redirection](https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/645) we implemented a feature that is causing a bug for our customers.

Currently the "oo_is_detailpage_redirection" filter is being overridden in the plugin, rendering it useless. Additionally, the plugin performs a redirect that removes parameters from URL, even when redirecting from the regular ID-URL to the "speaking" Title-URL (www.website.de/detail/123/ --> www.website.de/detail/123-house-in-aachen/)

The expected behavior is that the filter can be properly set to true or false and that the parameters in the URL remain intact even when the plugin performs a redirect. These changes are intended to restore the desired behavior of the plugin and improve the user experience.

Please revise the feature for any other bugs and inconsistencies.

**Comment by fredericalpers** [comment]
also see the linked [Pull Request](https://github.com/onOffice-Web-Org/oo-wp-plugin/pull/812)
