### ISSUE TITLE
Optional writing of tasks in onOffice enterprise with plugin forms & fields.

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#820]
# Optional writing of tasks in onOffice enterprise with plugin forms & fields

### Introduction
Currently, no tasks are created automatically, e.g. for incoming owner forms. In order to make the form functions more attractive and bring them up to a better standard, we would like to expand our forms.

### User Story
As a real estate agent, I would like the forms on my website, which I have integrated via the onOffice for WP-Websites plugin, to be able to automatically create tasks in onOffice enterprise. To do this, I need an enhancement to the plugin backend that allows me to enable or disable the automatic creation of tasks and specify what information should be used in the process. The use of the always available/possible fields, such as “Responsibility”, “Supervisor” or “Type”, is essential. In addition, I would like a graphical interface in the plugin backend that allows me to make these settings easily and intuitively for each form.

### Requirements / Tasks
- [x] Implementation of the graphical user interface (see design/screenshots)
- [x] Implementation of a function in the backend of the forms to activate or deactivate the automatic creation of tasks.
- [x] Integration of a function to select the fields from onOffice enterprise that are to be included in the automatic entries.
- [x] Test the functionality thoroughly to ensure that automatic tasks are created correctly and that the settings in the backend work properly.

[Tasks - onOffice API](https://apidoc.onoffice.de/api-calls-sorted-by-module/tasks/)

### Design / Screenshots
![aufgabenplugin (1)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/17a67890-ffdf-4529-8e9e-303afe0bae6d)

![aufgabenplugin-open (1)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/2596ce0e-0bde-4793-99af-bfcb60217c4f)

![aufgabenplugin-disabled (1)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/851e2277-dbe9-412c-9d1c-46dcdefce456)

**Comment by yeneastgate** [comment]
@fredericalpers I have implement it as you've mentioned. Please watch the demo video. Thank you

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/7ca4d3b5-fbcd-48f7-a4dc-ca98fcb78368

**Comment by fredericalpers** [comment]
@yeneastgate thank you :) we will review this as soon as possible

**Comment by fredericalpers** [comment]
Vorgezogen auf 5.2
