### ISSUE TITLE
Implement filtering in similar estates

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#824]
# Implement filtering in similar estates.

### User Story
As a real estate agent using the onOffice for WP-Websites Plugin, I encounter limitations with the "Similar Estates" template. Currently, I am unable to customize property filters/onOffice enterprise filters for this template. This leads to inaccurate suggestions on my real estate website, especially when managing multiple websites with different property types. To ensure that the "similar estate" template provides relevant and tailored suggestions to users, I require the capability to set property filters/onOffice enteprise filters directly in the settings for Similar estates.

The "similar estate" template serves a critical role in suggesting related properties to users visiting my website. However, the inability to customize the filters for this template poses challenges, particularly when managing multiple websites targeting distinct property segments. E.g. Luxury Properties and Ordinary Properties. To address these limitations and improve the accuracy of property suggestions, I propose the implementation of allowing filtering in similar estates.

By introducing this feature, the onOffice for WP-Websites Plugin can significantly enhance the accuracy and relevance of property suggestions provided by the "similar estates" template. This customization capability empowers me to create a more engaging and user-centric experience on my real estate website, ensuring that visitors receive pertinent property recommendations based on their interest and preferences.

### Requirements / Tasks
- [x] The Plugin should provide an option to set filters within the settings of "Similar estates" .

### Design / Screenshots
![similarestates_filter (1)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/3495490a-17e8-4745-ba2c-4806ec702bde)
![similarestates_filter2 (1)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/dbd27cf2-dc18-4576-90be-fe00f0f8d227)
![similarestates_filter3 (1)](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/74d238ca-320b-4ce0-98f6-82be82aa073b)

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented and here is video evidence: https://files.fm/u/gmyrzbeht8#/view/86kc3huxd8. Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
Thank you, we will review this as soon as possible :)
