### ISSUE TITLE
Enhancement of the  detail page functionality - contact person selection for detail page

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#835]
# Enhancement of the detail page functionality - contact person selection for detail page

### Introduction
Currently, all contact persons of the type broker defined for a property in onOffice enterprise are transferred to the website and displayed with the selected fields from the field list.

### User Story
As a real estate agent, I would like to have a new selection box in the settings for the detailed view in the onOffice for WP Websites plugin that allows me to choose between “All contact persons” and “Main contact person”.

This should be realized by a radio select field, so that I can flexibly determine whether all contact persons or only the main contact person are displayed on the detail pages. This functionality helps me to better control the presentation of my properties and the presentation of my team and to offer potential customers more targeted information.

### Requirements / Tasks

- [x] Development of the new box with Radio Buttons Select in the settings of the detail page below “Additional media”.
- [x] Options: Show all contact persons (as the selected default) and Show main contact person only.
- [x] Add information text: "The main contact person is the address data record of the broker type, which is stored in the first place in onOffice enterprise."
- [x] Carry out tests to ensure that the change has no backwards compatibility issues.

### Design / Screenshots
![asp3](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/1b0f2717-6649-4ef2-a297-8f13d3427983)

**Comment by yeneastgate** [comment]
@fredericalpers When implementing, we have found some issues, please answer the following:
1. For the Contact person box in the backend:
+ Ansprechpartner/ Ansprechpartnerin
+ Alle Ansprechpartner/Ansprechpartnerinnen anzeigen
+ Nur Hauptansprechpartner/Hauptansprechpartnerin anzeigen
We tried translating and found that the meaning of each pair of words is the same. What do you want to display in English?
2. For "Show all contact persons", do you want to display all contact persons or only all contact persons whose contact type is "Broker" 
![Screenshot 2024-06-18 152706](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/104892108/a90dd4f7-4d9b-4caa-ac54-cf6d6646137f)

**Comment by fredericalpers** [comment]
@yeneastgate >For the Contact person box in the backend:

In german we differentiate between female and male. In english the headline of the box would just be: "Contact person".

For the select it would be:

- Show all contact person
- Only show main contact person 

>For "Show all contact persons", do you want to display all contact persons or only all contact persons whose contact type is "Broker"

It should only display the contact person of type broker.

**Comment by yeneastgate** [comment]
@fredericalpers I got it, thanks for your explanation

**Comment by yeneastgate** [comment]
@fredericalpers I implemented this issue and here is the evidence: https://files.fm/f/g5yzzdmas2. Please check and let me know your opinion. Thanks!
