### ISSUE TITLE
Proper Handling of Image Type Selection in Property List Settings

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#851]
# Proper Handling of Image Type Selection in Property List Settings

### User Story
As an admin user of the onOffice WordPress plugin, I want the backend to accurately reflect when all image types are deselected in the property list settings, so that it is clear no images will be displayed on the frontend.

Currently, in the settings for the property list, admins can choose different types of images to display. If all image types are deselected, the frontend correctly shows no images. However, in the backend, the selection still shows as "Title Image (TITELBILD)" This causes confusion, as the backend should also indicate that no images are selected when all options are deselected.

By implementing this fix, admin users will have a clearer and more accurate understanding of the image display settings in the property lists, leading to a better user experience and fewer misunderstandings.

### Tasks / Requirements

- [x] Adjust the settings handling to ensure that when all image types are deselected, the backend reflects this accurately.
- [x] Test cases for deselecting all image types and verifying that the backend shows no selected image types.

**Comment by fredericalpers** [comment]
The checkbox for the image type "TITELBILD" is checked by default in the backend of the plugin. However, when I deselect this checkbox and save the settings, it appears as still being checked in the backend. Despite this, no "TITELBILD" image is displayed on the frontend, the whole "oo-listimage" will be removed from the code.

There seems to be an issue in the code causing this inconsistency: the checkbox remains checked by default in the backend but does not display the "TITELBILD" image on the frontend when it is deselected. See screenshots below. The TITELBILD should stay the default selected image type for the property lists, only when actively deselected the checkbox needs to stay deselected.


![titelbild-yes](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/92b45927-6b51-4b0d-8a7c-d1df27e8ffd0)

![titelbild-no](https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/88546396/37ed8276-6ee9-40d8-a753-ba2def519a0d)

**Comment by dai-eastgate** [comment]
@fredericalpers I have fixed the bug, here is evidence 

https://github.com/onOffice-Web-Org/oo-wp-plugin/assets/106214469/45ab0e9a-61c4-4c31-978b-86d9525426c3

Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
Seems to be working! Thank you :) we will review this as soon as possible

**Comment by miauzjpg** [comment]
> Note: Currently, I see that the admin Detail View and admin Similar Estates pages are also encountering this error. Do you want to fix the Estate Details View and Similar Estate as well?

yes. Can you fix Similar Estates View and Estate Details? 
Estate Details: If you deselect all photo types and then save, all photo types will be selected again.

**Comment by miauzjpg** [comment]
> Note: Currently, I see that the admin Detail View and admin Similar Estates pages are also encountering this error. Do you want to fix the Estate Details View and Similar Estate as well?

yes. Can you fix Similar Estates View and Estate Details? 
Estate Details: If you deselect all photo types and then save, all photo types will be selected again.

**Comment by dai-eastgate** [comment]
> > Note: Currently, I see that the admin Detail View and admin Similar Estates pages are also encountering this error. Do you want to fix the Estate Details View and Similar Estate as well?
> 
> yes. Can you fix Similar Estates View and Estate Details? Estate Details: If you deselect all photo types and then save, all photo types will unfortunately be selected again.

I fixed it. Please take a look at my demo video and let me know your opinions. Thanks!
https://files.fm/u/ut8q79xswm#/view/fuf8suxd9d

**Comment by miauzjpg** [comment]
> > > Note: Currently, I see that the admin Detail View and admin Similar Estates pages are also encountering this error. Do you want to fix the Estate Details View and Similar Estate as well?
> > 
> > 
> > yes. Can you fix Similar Estates View and Estate Details? Estate Details: If you deselect all photo types and then save, all photo types will unfortunately be selected again.
> 
> I fixed it. Please take a look at my demo video and let me know your opinions. Thanks! https://files.fm/u/ut8q79xswm#/view/fuf8suxd9d

yeah, looks good! Could you fix the conflicting file in the Pull Request? Then we will review this as soon as possible :)

**Comment by dai-eastgate** [comment]
@miauzjpg I fixed the conflict. Please help us to review. Thanks!
