### ISSUE TITLE
Implementation of a checkbox to change the form behavior

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#871]
# Implementation of a checkbox to change the form behavior

### User Story
As an real estate agent, I would like to have a checkbox in the backend that allows me to decide whether the ownerleadgeneratorform.php multi-page form is displayed as modal or normally embedded on the website, so I can customize the user experience as needed. This feature enables flexible customization of the user experience, which is important for different use cases and user preferences.

### Tasks / Requirements

- [x] Implement a new checkbox in the backend called “Show form as modal”. The checkbox is activated by default, which means that the form is displayed as a modal by default for backwards compatibility reasons.
- [x] If the checkbox is deactivated, the form is not integrated in the modal but on the website and still remains multi-page.

**Comment by fredericalpers** [comment]
@yeneastgate I can confirm both your points. The checkbox should be located in Layout & Design. The default state should be active to avoid problems with backwars compatibility. Thank you :)

**Comment by yeneastgate** [comment]
@fredericalpers  I have implemented it. This is video demo 

https://github.com/user-attachments/assets/d00edec1-dfd5-4877-ba4d-ff519059b360

Please check and let me know your opinion. Thanks!

**Comment by fredericalpers** [comment]
@yeneastgate seems to be working properly, thank you :) we will review this as soon as possible
