### ISSUE TITLE
⚠️Bug fix for displaying reference property detail pages after Release v5.1⚠️

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#903]
# ⚠️Bug fix for displaying reference property detail pages after Release v5.1⚠️

### User Story
In plugin version 5.1, attempts to access the detail page of a property marked as “Reference” trigger a redirect to the 404 page. The settings specify that reference properties are displayed in the list. Access to reference properties is not restricted, i.e. the option “Restrict access to reference properties (404 Not found)” is deactivated. This configuration worked correctly in plugin version 5.0.

If the option “Restrict access to reference properties (404 Not found)” is **deactivated**, the corresponding detail page should be loaded correctly when clicking on a reference property. There should be no redirection to the 404 page.

This user story ensures that the existing bug in plugin version 5.1 is fixed and the expected behavior in relation to reference properties is restored.

Example URL of the property list: [Property List](https://testinstanz-mr.onofficeweb.com/immobilien/)
Example URL of the detail page: [Detail page](https://testinstanz-mr.onofficeweb.com/immobilien/detail/59-archiviert-mietwohnung-mit-schoenem-bad/)

### Task / Requirements

- [x] Analysis of the code for error identification
- [x] It must be ensured that the changes are compatible with the existing plugin version 5.1.

**Comment by fredericalpers** [comment]
@yeneastgate @dai-eastgate please prioritize this bug so that we can fix and release it as soon as possible

**Comment by dai-eastgate** [comment]
@fredericalpers yes, I will check it now.

**Comment by dai-eastgate** [comment]
@fredericalpers I fixed this bug, please take a look at my demo video. Thanks! 

https://github.com/user-attachments/assets/1dca3696-9970-4dac-a70e-31d77de31aa6
