### ISSUE TITLE
Custom Labels for Address Lists and Address List Detail Page in the onOffice for WP Plugin

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#912]
# Custom Labels for Address Lists and Address List Detail Page in the onOffice for WP Plugin

### User Story
As an administrator of the onOffice for WP Plugin, I want to add the ability to use custom labels for address lists and the address list detail page, similar to how it is done for properties, so that I can rename specific fields and improve user-friendliness.

The onOffice for WP Plugin currently allows the use of custom labels for property fields to display customized field names. This functionality should now be extended to address lists and their detail pages, enabling the renaming of fields as needed. Administrators should have the flexibility to define specific labels for different fields so that the frontend can display labels that fit the particular requirements of the user.

This functionality provides significant value to users by allowing them to customize the field names for address lists according to their specific needs. It is especially important for use cases where the plugin is used in various contexts, making flexibility a key requirement.

### Task / Requirements

- [x] Administrators can define custom labels for fields in address lists and adress detail pages, similar to how it's done for properties
- [x] If no custom labels are defined, the system will fall back to the default field names to ensure smooth migration for existing installations.

**Comment by fredericalpers** [comment]
@yeneastgate @dai-eastgate If possible resolve this issue beginning of next week. Thank you :)

**Comment by dai-eastgate** [comment]
@fredericalpers Please look at my demo video and let me know your opinions. Thanks!

https://github.com/user-attachments/assets/28c71231-80d6-4ad9-b9fb-b84557526310

**Comment by fredericalpers** [comment]
@dai-eastgate seems to be working fine! thank you :) we will review this as soon as possible
