### ISSUE TITLE
 reCAPTCHA script is being loaded in plugin settings where it shouldn't

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#941]
I’ve noticed that in the plugin settings, the reCAPTCHA script is being loaded, even though there’s no need for it in this section of the plugin. Since reCAPTCHA is not required here, loading the script is unnecessary and could potentially affect performance.

Could you please prevent the reCAPTCHA script from being loaded in the plugin settings area?

**Comment by yeneastgate** [comment]
@fredericalpers Are you asking about loading reCAPTCHA on this page? 

![image](https://github.com/user-attachments/assets/7784ca56-01bd-4c9e-9ac7-646d45696d1f)

The reCAPTCHA script in the plugin settings verifies the reCAPTCHA keys when the user inputs the "site key" and "secret key".

**Comment by fredericalpers** [comment]
@andernath
