### ISSUE TITLE
"Helper Class" with Translatable Text for Address Detail Page

### ISSUE THREAD

**Issue by fredericalpers** [onOffice-Web-Org/oo-wp-plugin#946]
# "Helper Class" with Translatable Text for Address Detail Page

### User story
Implement a "helper class" with translatable text that will handle cases when the address detail page is accessed without a dataset number. This functionality should be built similarly to the implementation on the real estate detail page.

https://github.com/onOffice-Web-Org/oo-wp-plugin/blob/4e26567b83efd088cd44114d946448c3438bd7ff/plugin/Controller/ContentFilter/ContentFilterShortCodeEstateDetail.php#L112

Please ensure consistency with existing project patterns and code style. Feel free to reuse code from the property detail page where applicable.

**Comment by dai-eastgate** [comment]
@fredericalpers Would you like me to implement this feature as seen in the property details? Here’s how it would work:

- **Case 1**: If the user is logged in, show a random address ID.
![image](https://github.com/user-attachments/assets/a96c1cf7-ea71-406f-9f72-a5ea0cc367ae)


- **Case 2**: If the user is not logged in, do not display the address ID.
![image](https://github.com/user-attachments/assets/1f7c64b6-68cf-4e86-bdf8-73c23d3e8569)


If this is correct, should I also change the terminology—for example, replacing "estate" with "address"?

**Comment by fredericalpers** [comment]
@dai-eastgate yes, please go ahead and implement it as it is with properties. Please change the terminology to "address"

**Comment by dai-eastgate** [comment]
@fredericalpers If no addressID is found, please provide me a document link, similar to when an estateID is not found. 
![image](https://github.com/user-attachments/assets/026bc990-886e-4c87-9986-3c588b786fff)
https://wp-plugin.onoffice.com/en/first-steps/estate-lists/

**Comment by fredericalpers** [comment]
@dai-eastgate we do not have a specific part about adresslists in our documentation yet. Please link to the main page for now, thank you :)

**Comment by dai-eastgate** [comment]
@fredericalpers I have implemented it. Please take a look at my demo video and let me know your opinions. Thanks! 

https://github.com/user-attachments/assets/286b1590-2477-4515-8fcc-d7fd6beed077

**Comment by fredericalpers** [comment]
@dai-eastgate thank you :)

🔴 I had to remove the video, since you showed your excel sheet with login credentials. Please be more careful with posting these videos and showing login credentials and API Tokens in the future. 🔴

**Comment by dai-eastgate** [comment]
@fredericalpers Sorry. I will be carefull next time
